// apps/web/src/views/wflow/pages/admin/InstanceFormDataManager.vue
<script setup>
import {getModelFormFields, getProcGroupItemsList} from "@/api/model.js";
import {exportInstWithFormByCode, getInstWithFormByCode} from "@/api/instance.js";
import {ElMessage} from "element-plus";
import WAvatar from "../../common/WAvatar.vue";
import {$debounce, ajaxDownload, getRes, isEmpty} from "@/utils/GlobalFunc.js";
import ValueType from "../../design/form/ValueType.js";
import WDialog from "../../common/WDialog.vue";
import {sanitizeHtml} from "@/utils/html.ts";

const datas = ref({
  records: [],
  pages: 0,
  total: 0
})
const actives = ref([])
const modelGroupList = ref([])
const activeModel = ref()
const tbCellStyle = {
  background: 'var(--el-fill-color-lighter)',
  padding: '10px 0',
}
const fieldMap = new Map()
const modelFields = ref([])
const dataGroups = ref([])
const search = ref(null)
const loading = ref(false)
const params = reactive({
  pageSize: 10,
  pageNo: 1,
  status: null,
  code: null,
  title: null,
  fieldKey: null,
  fieldValue: null,
  compare: null,
  startRange: [],
  endRange: [],
})

const compares = [
  {label: '模糊匹配', value: 'LIKE'},
  {label: '等于', value: 'EQ'},
  {label: '不等于', value: 'NEQ'},
  {label: '大于', value: 'GT'},
  {label: '大于等于', value: 'GE'},
  {label: '小于', value: 'LT'},
  {label: '小于等于', value: 'LE'}
]

const fieldDetail = reactive({
  dialog: false,
  field: {},
  value: null
})

onMounted(() => getModelGroupList())
const _loadDataGroups = $debounce(loadDataGroups, 800)

function getModelGroupList() {
  getProcGroupItemsList().then(res => {
    modelGroupList.value = res.data.filter(v => v.items.length > 0).map(group => {
      group.items.forEach(v => v.logo = JSON.parse(v.logo))
      return group
    })
    dataGroups.value = modelGroupList.value
    _loadDataGroups()
  })
}

function loadDataGroups() {
  if (isEmpty(search.value)){
    dataGroups.value = modelGroupList.value
  } else {
    dataGroups.value = modelGroupList.value.map(obj => {
      const filteredItems = obj.items.filter(item =>
          item.procName.includes(search.value)
      );
      return { ...obj, items: filteredItems };
    }).filter(obj => obj.items.length > 0);
  }
}

function getInstFormList() {
  if (!activeModel.value) {
    ElMessage.warning('请先在左侧指定流程类型')
    return
  }
  loading.value = true
  params.code = activeModel.value
  const _params = Object.assign({}, params)
  _params.startRange = _params.startRange ? String(_params.startRange) : []
  _params.endRange = _params.endRange ? String(_params.endRange) : []
  getInstWithFormByCode(_params).then(res => {
    loading.value = false
    datas.value = res.data
    //把字段转对象
    datas.value.records.forEach(v => {
      if (Array.isArray(v.fieldData)) {
        const obj = {};
        (v.fieldData || []).forEach(field => {
          obj[field.key] = field
        })
        v.fieldData = obj
      } else {
        Object.keys(v.fieldData).forEach(key => {
          v.fieldData[key] = {
            key,
            value: v.fieldData[key]
          }
        })
      }
    })
  }).catch(err => {
    loading.value = false
    ElMessage.error(err.msg)
  })
}

function getFormFields(call) {
  getModelFormFields(activeModel.value).then(rsp => {
    modelFields.value.length = 0
    const subFields = []
    fieldMap.clear()
    rsp.data.forEach(v => {
      if (v.valueType === ValueType.none) return;
      if (v.parent) subFields.push(v)
      else {
        modelFields.value.push(v)
        fieldMap.set(v.key, v)
      }
    })
    subFields.forEach(v => {
      const parent = fieldMap.get(v.parent.key)
      if (parent) {
        if (!parent.children) parent.children = []
        parent.children.push(v)
      }
    })
    if(call) call()
  }).catch(err => {
    ElMessage.error(err.msg)
  })
}

function getFieldValue(field, val) {
  switch (field.valueType) {
    case ValueType.option:
      return val?.label
    case ValueType.options:
      return (val || []).map(v => v.label).join('、')
    case ValueType.timeRange:
    case ValueType.dateTimeRange:
      return Array.isArray(val) ? `${val[0]} ~ ${val[1]}` : ''
    case ValueType.orgArray:
      return (val || []).map(v => v.name).join('、')
    case ValueType.org:
      return val?.name
    case ValueType.array:
      return Array.isArray(val) ? val.join('、') : (val || '')
    case ValueType.user:
      return val?.name
    case ValueType.image:
      return isEmpty(val) ? '' : `<img src="${val}" style="width: 50px; height: 50px; margin: 2px"/>`
    case ValueType.imageArray:
      return (val || []).map(v => `<img src="${getRes(v.url)}?zip=true" style="width: 50px; height: 50px; margin: 2px"/>`).join('')
    case ValueType.fileArray:
      return (val || []).map(v => `<a href="${getRes(v.url)}?download=true" style="margin: 2px">${v.name}</a>`).join('')
    case ValueType.object:
      switch (field.type) {
        case 'PhoneNumber':
          return `+${val?.prefix} ${val?.number}`
      }
      return JSON.stringify(val)
    case ValueType.all:
      return parserAllTypeVal(field, val)
    default:
      return val
  }
}

function parserAllTypeVal(field, val) {
  return JSON.stringify(val)
}

function exportData(){
  if ((params.code || '') === ''){
    ElMessage.warning('请先在左侧选择流程')
    return
  }
  const _params = Object.assign({}, params)
  _params.startRange = _params.startRange ? String(_params.startRange) : []
  _params.endRange = _params.endRange ? String(_params.endRange) : []
  exportInstWithFormByCode(_params).then(rsp => {
    ajaxDownload(rsp)
    ElMessage.success('导出成功')
  }).catch(err => {
    ElMessage.error(err.msg)
  })
}

function showDetail(field, value) {
  fieldDetail.field = field
  fieldDetail.value = value
  fieldDetail.dialog = true
}

watch(activeModel, () => {
  params.fieldKey = null
  params.fieldValue = null
  params.compare = null
  params.pageNo = 1
  getFormFields(() => {
    getInstFormList()
  })
})

watch(search, _loadDataGroups)
</script>

<template>
  <el-row class="w-card" :gutter="20">
    <el-col :span="4" style="border-right: 1px solid var(--el-border-color)">
      <el-input v-model="search" clearable prefix-icon="search" placeholder="搜索流程" style="padding-bottom: 10px"/>
      <el-scrollbar>
        <el-collapse v-model="actives">
          <el-collapse-item :key="group.id" v-for="group in dataGroups" :name="group.id">
            <template #title>
              <el-text truncated>{{ group.name }}</el-text>
            </template>
            <div class="w-group-apps">
              <el-text @click="activeModel = app.code" truncated :key="app.code"
                       v-for="app in group.items" :type="activeModel === app.code ? 'primary':''" tag="div">
                {{ app.procName }}
              </el-text>
            </div>
          </el-collapse-item>
        </el-collapse>
      </el-scrollbar>
    </el-col>
    <el-col :span="20" v-loading="loading">
      <el-space wrap class="w-form-data-operation">
        <el-button icon="Share" @click="exportData">导出数据</el-button>
        <el-select prefix-icon="Search" clearable v-model="params.status" style="width: 120px;" placeholder="流程状态">
          <el-option label="进行中" value="RUNNING"/>
          <el-option label="被驳回" value="REFUSE"/>
          <el-option label="已撤销" value="REVOKED"/>
          <el-option label="审批通过" value="PASS"/>
        </el-select>
        <el-input prefix-icon="Search" v-model="params.title" style="width: 250px;"
                  placeholder="搜索 发起人、流程类型"></el-input>
        <el-date-picker v-model="params.startRange" style="width: 300px;" type="daterange" start-placeholder="提交开始时间"
                        value-format="YYYY-MM-DD HH:mm" end-placeholder="提交结束时间"/>
        <el-date-picker v-model="params.endRange" style="width: 300px;" type="daterange" start-placeholder="完成开始时间"
                        value-format="YYYY-MM-DD HH:mm" end-placeholder="完成结束时间"/>
        <el-input clearable placeholder="输入搜索/比较值" v-model="params.fieldValue">
          <template #prepend>
            <el-select placeholder="选择字段" style="width: 120px;" v-model="params.fieldKey">
              <el-option :label="field.name" :value="field.key" v-for="field in modelFields" :key="field.key"/>
            </el-select>
          </template>
          <template #append>
            <el-select placeholder="判断关系" style="width: 100px;" v-model="params.compare">
              <el-option :label="cp.label" :value="cp.value" v-for="cp in compares" :key="cp.value"/>
            </el-select>
          </template>
        </el-input>
        <el-button type="primary" icon="Search" @click="getInstFormList">查询</el-button>
      </el-space>
      <el-scrollbar>
        <el-table border :data="datas.records" :cell-style="{padding: '5px 0'}" :header-cell-style="tbCellStyle">
          <el-table-column min-width="100" prop="defineName" label="流程类型" ></el-table-column>
          <el-table-column show-overflow-tooltip prop="title" label="标题"></el-table-column>
          <el-table-column show-overflow-tooltip prop="instId" label="流水号"></el-table-column>
          <el-table-column :show-overflow-tooltip="field.valueType !== ValueType.imageArray" min-width="100" prop="fieldData"
                           :label="field.name" v-for="field in modelFields" :key="field.key">
            <template #default="scope">
              <el-button link icon="View" type="primary" v-if="field.children && (scope.row.fieldData[field.key] || {})?.value?.length > 0"
                         @click="showDetail(field, (scope.row.fieldData[field.key] || {}).value)">
                查看
              </el-button>
              <div style="display:flex;" v-else v-html="sanitizeHtml(getFieldValue(field, (scope.row.fieldData[field.key] || {}).value))"></div>
            </template>
          </el-table-column>
          <el-table-column width="120" prop="initiator" label="发起人">
            <template #default="scope">
              <w-avatar :id="scope.row.initiator.id" :name="scope.row.initiator.name" :src="scope.row.initiator.avatar" status="agent" :show-status="scope.row.isAgent"/>
            </template>
          </el-table-column>
          <el-table-column min-width="120" show-overflow-tooltip prop="startDept" label="发起部门"></el-table-column>
          <el-table-column prop="currentNodeName" min-width="100" label="当前节点"></el-table-column>
          <el-table-column label="状态" width="100">
            <template #default="scope">
              <el-tag v-if="scope.row.status === 'RUNNING'" type="primary">进行中</el-tag>
              <el-tag v-else-if="scope.row.status === 'REFUSE'" type="danger">被驳回</el-tag>
              <el-tag v-else-if="scope.row.status === 'REVOKED'" type="info">已撤销</el-tag>
              <el-tag v-else-if="scope.row.status === 'PASS'" type="success">审批通过</el-tag>
            </template>
          </el-table-column>
          <el-table-column min-width="150" show-overflow-tooltip prop="createTime" label="提交时间"></el-table-column>
          <el-table-column min-width="150" show-overflow-tooltip prop="endTime" label="结束时间"></el-table-column>
        </el-table>
        <div style="margin-top: 20px; display: flex; justify-content: right">
          <el-pagination v-model:current-page="params.pageNo"
                         v-model:page-size="params.pageSize"
                         :page-sizes="[10, 20, 50, 100]"
                         :disabled="datas.pages === 0"
                         layout="total, sizes, prev, pager, next"
                         :total="datas.total" background
                         @size-change="getInstFormList"
                         @current-change="getInstFormList"/>
        </div>
      </el-scrollbar>
    </el-col>
    <w-dialog close-free :show-ok="false" :title="`${fieldDetail.field.name}：详情`" v-model="fieldDetail.dialog">
      <el-table border  :data="fieldDetail.value" :cell-style="{padding: '5px 0'}" :header-cell-style="tbCellStyle">
        <el-table-column :label="field.name" :prop="field.key" v-for="field in fieldDetail.field.children" :key="field.key">
          <template #default="scope">
            <div v-html="sanitizeHtml(getFieldValue(field, scope.row[field.key]))"></div>
          </template>
        </el-table-column>
      </el-table>
    </w-dialog>
  </el-row>
</template>

<style scoped lang="less">
.w-form-data-operation {
  margin-bottom: 10px;
}

.w-group-apps {
  & > * {
    display: block;
    width: 100%;
    cursor: pointer;
    padding: 0 10px;
    border-radius: 5px;

    &:hover {
      background-color: var(--el-color-primary-light-9);
    }
  }
}
</style>

// apps/web-react/src/views/admin/InstanceFormDataManager.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  Button,
  Card,
  Cascader,
  DatePicker,
  Input,
  Modal,
  Select,
  Space,
  Table,
  Tag,
  Typography,
  message,
} from 'antd';
import type { TableColumnsType } from 'antd';
import { DownloadOutlined, EyeOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import dayjs, { type Dayjs } from 'dayjs';
import { getProcGroupItemsList, getModelFormFields } from '@/api/model';
import { getInstWithFormByCode, exportInstWithFormByCode } from '@/api/instance';
import { downloadBlob } from '@/api/request';
import { resUrl } from '@/utils/resource';
import { WAvatar } from '@/components/WAvatar';
import { useTranslation } from '@/i18n';

interface GroupOption {
  value: string;
  label: string;
  children: Array<{ value: string; label: string }>;
}

const statusTag = (tr: (key: string) => string, status: string) => {
  switch (status) {
    case 'RUNNING':
      return <Tag color="processing">{tr('admin.status.running')}</Tag>;
    case 'SUSPEND':
      return <Tag color="warning">{tr('admin.status.suspended')}</Tag>;
    case 'REFUSE':
      return <Tag color="error">{tr('admin.status.refused')}</Tag>;
    case 'REVOKED':
      return <Tag color="default">{tr('admin.status.revoked')}</Tag>;
    case 'PASS':
      return <Tag color="success">{tr('admin.status.passed')}</Tag>;
    case 'EXCEPTION':
      return <Tag color="volcano">{tr('admin.status.exception')}</Tag>;
    default:
      return <Tag>{status || tr('admin.status.unknown')}</Tag>;
  }
};

const asAttachment = (tr: (key: string) => string, entry: any, fallbackName?: string) => {
  if (entry && typeof entry === 'object') {
    return { url: String(entry.url ?? ''), name: String(entry.name ?? fallbackName ?? tr('admin.instanceFormData.attachment')) };
  }
  return { url: String(entry ?? ''), name: fallbackName || String(entry ?? tr('admin.instanceFormData.attachment')) };
};

const renderFieldValue = (
  tr: (key: string) => string,
  value: any,
  valueType?: string,
  type?: string
): React.ReactNode => {
  if (value === null || value === undefined || value === '') return '-';
  switch (valueType) {
    case 'option':
      return value?.label ?? value?.name ?? String(value);
    case 'options':
      return (Array.isArray(value) ? value : [value])
        .map((item: any) => item?.label ?? item?.name ?? item)
        .join('、');
    case 'timeRange':
    case 'dateTimeRange':
      return Array.isArray(value) ? `${value[0] ?? ''} ~ ${value[1] ?? ''}` : String(value);
    case 'org':
      return value?.name ?? '-';
    case 'orgArray':
      return (value || [])
        .map((item: any) => item?.name)
        .filter(Boolean)
        .join('、') || '-';
    case 'array':
      return Array.isArray(value)
        ? value.map((item: any) => (item && typeof item === 'object' ? item?.name ?? item?.label ?? '' : item)).join('、')
        : String(value);
    case 'image': {
      const file = asAttachment(tr, value, tr('admin.instanceFormData.image'));
      return <img src={resUrl(file.url)} style={{ width: 50, height: 50, margin: 2, objectFit: 'cover' }} />;
    }
    case 'imageArray':
      return (
        <Space size={2} wrap>
          {(Array.isArray(value) ? value : [value]).map((entry: any, index: number) => {
            const file = asAttachment(tr, entry, tr('admin.instanceFormData.imageName').replace('{index}', String(index + 1)));
            return (
              <a key={`${file.url}-${index}`} href={resUrl(file.url)} target="_blank" rel="noreferrer">
                <img
                  src={resUrl(file.url, { zip: 'true' })}
                  style={{ width: 50, height: 50, margin: 2, objectFit: 'cover' }}
                />
              </a>
            );
          })}
        </Space>
      );
    case 'fileArray':
      return (
        <Space size={4} wrap>
          {(Array.isArray(value) ? value : [value]).map((entry: any, index: number) => {
            const file = asAttachment(tr, entry, tr('admin.instanceFormData.attachmentName').replace('{index}', String(index + 1)));
            return (
              <a key={`${file.url}-${index}`} href={resUrl(file.url, { download: 'true' })} target="_blank" rel="noreferrer">
                {file.name}
              </a>
            );
          })}
        </Space>
      );
    case 'object':
      if (type === 'PhoneNumber') return `+${value?.prefix ?? ''} ${value?.number ?? ''}`.trim();
      return value?.name ?? value?.label ?? JSON.stringify(value);
    default:
      if (typeof value === 'object') return value?.name ?? value?.label ?? JSON.stringify(value);
      return String(value);
  }
};

export const InstanceFormDataManager: React.FC = () => {
  const { t } = useTranslation();
  const statusOptions = [
    { label: t('admin.status.running'), value: 'RUNNING' },
    { label: t('admin.status.suspended'), value: 'SUSPEND' },
    { label: t('admin.status.refused'), value: 'REFUSE' },
    { label: t('admin.status.revoked'), value: 'REVOKED' },
    { label: t('admin.status.passed'), value: 'PASS' },
    { label: t('admin.status.exception'), value: 'EXCEPTION' },
  ];
  const compareOptions = [
    { label: t('admin.instanceFormData.compareLike'), value: 'LIKE' },
    { label: t('admin.instanceFormData.compareEq'), value: 'EQ' },
    { label: t('admin.instanceFormData.compareNeq'), value: 'NEQ' },
    { label: t('admin.instanceFormData.compareGt'), value: 'GT' },
    { label: t('admin.instanceFormData.compareGe'), value: 'GE' },
    { label: t('admin.instanceFormData.compareLt'), value: 'LT' },
    { label: t('admin.instanceFormData.compareLe'), value: 'LE' },
  ];
  const [groups, setGroups] = useState<GroupOption[]>([]);
  const [modelKeyword, setModelKeyword] = useState('');

  const [codePath, setCodePath] = useState<string[] | undefined>(undefined);
  const code = codePath && codePath.length > 0 ? String(codePath[codePath.length - 1]) : undefined;
  const [status, setStatus] = useState<string | undefined>(undefined);
  const [startRange, setStartRange] = useState<[Dayjs, Dayjs] | null>(null);
  const [fieldKey, setFieldKey] = useState<string | undefined>(undefined);
  const [compare, setCompare] = useState<string | undefined>('LIKE');
  const [fieldValue, setFieldValue] = useState('');
  const [fieldOptions, setFieldOptions] = useState<Array<{ label: string; value: string }>>([]);

  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [records, setRecords] = useState<any[]>([]);
  const [total, setTotal] = useState(0);
  const [pageNo, setPageNo] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [reloadToken, setReloadToken] = useState(0);
  const [detailRecord, setDetailRecord] = useState<any | null>(null);

  const filtersRef = useRef({
    code: undefined as string | undefined,
    status: undefined as string | undefined,
    startRange: null as [Dayjs, Dayjs] | null,
    fieldKey: undefined as string | undefined,
    compare: 'LIKE' as string | undefined,
    fieldValue: '',
  });
  filtersRef.current = { code, status, startRange, fieldKey, compare, fieldValue };

  useEffect(() => {
    getProcGroupItemsList()
      .then((res) => {
        const options: GroupOption[] = (res.data || [])
          .filter((group: any) => group.items?.length)
          .map((group: any) => ({
            value: String(group.id),
            label: group.name,
            children: group.items.map((item: any) => ({ value: String(item.code), label: item.procName })),
          }));
        setGroups(options);
      })
      .catch((e: any) => message.error(e?.msg || t('admin.instanceFormData.fetchGroupsFailed')));
  }, []);

  const cascaderOptions = useMemo(() => {
    const term = modelKeyword.trim();
    if (!term) return groups;
    return groups
      .map((group) => ({
        ...group,
        children: group.children.filter((item) => item.label.includes(term)),
      }))
      .filter((group) => group.children.length > 0);
  }, [groups, modelKeyword]);

  const dynamicFields = useMemo(() => {
    const map = new Map<string, { key: string; name: string; valueType?: string; type?: string }>();
    records.forEach((record: any) => {
      (record.fieldData || []).forEach((field: any) => {
        if (field?.key && !map.has(field.key)) map.set(field.key, field);
      });
    });
    return Array.from(map.values());
  }, [records]);

  const buildQueryParams = useCallback(() => {
    const f = filtersRef.current;
    const params: Record<string, any> = {};
    if (f.code) params.code = f.code;
    if (f.status) params.status = f.status;
    if (f.startRange?.[0] && f.startRange[1]) {
      params.startRange = `${f.startRange[0].format('YYYY-MM-DD HH:mm')},${f.startRange[1].format('YYYY-MM-DD HH:mm')}`;
    }
    if (f.fieldKey && f.fieldValue) {
      params.fieldKey = f.fieldKey;
      params.compare = f.compare || 'LIKE';
      params.fieldValue = f.fieldValue;
    }
    return params;
  }, []);

  const loadData = useCallback(
    async (page: number, size: number) => {
      if (!code) {
        setRecords([]);
        setTotal(0);
        return;
      }
      setLoading(true);
      try {
        const res = await getInstWithFormByCode({ ...buildQueryParams(), pageNo: page, pageSize: size });
        const data = res.data || {};
        setRecords(data.records || []);
        setTotal(data.total || 0);
      } catch (e: any) {
        message.error(e?.msg || t('admin.instanceFormData.fetchDataFailed'));
      } finally {
        setLoading(false);
      }
    },
    [code, buildQueryParams]
  );

  useEffect(() => {
    void loadData(pageNo, pageSize);
  }, [pageNo, pageSize, code, reloadToken, loadData]);

  const handleCodeChange = async (next?: string[]) => {
    const path = next && next.length > 0 ? next : undefined;
    const value = path ? String(path[path.length - 1]) : undefined;
    setCodePath(path);
    setFieldKey(undefined);
    setCompare('LIKE');
    setFieldValue('');
    setPageNo(1);
    if (!value) {
      setFieldOptions([]);
      return;
    }
    try {
      const res = await getModelFormFields(value);
      const options = (res.data || [])
        .filter((field: any) => !field.parent && field.valueType !== 'none')
        .map((field: any) => ({ label: field.name || field.key, value: String(field.key) }));
      setFieldOptions(options);
    } catch (e: any) {
      setFieldOptions([]);
      message.error(e?.msg || t('admin.instanceFormData.fetchFieldsFailed'));
    }
  };

  const handleSearch = () => {
    if (!code) {
      message.warning(t('admin.instanceFormData.selectProcessType'));
      return;
    }
    if (pageNo === 1) setReloadToken((token) => token + 1);
    else setPageNo(1);
  };

  const handleReset = () => {
    setModelKeyword('');
    setCodePath(undefined);
    setStatus(undefined);
    setStartRange(null);
    setFieldKey(undefined);
    setCompare('LIKE');
    setFieldValue('');
    setFieldOptions([]);
    setRecords([]);
    setTotal(0);
    setPageNo(1);
  };

  const handleExport = async () => {
    if (!code) {
      message.warning(t('admin.instanceFormData.selectProcessType'));
      return;
    }
    setExporting(true);
    try {
      const res: any = await exportInstWithFormByCode(buildQueryParams());
      const disposition = res?.headers?.['content-disposition'] as string | undefined;
      const match = disposition ? /filename\*=UTF-8''([^;]+)/i.exec(disposition) : null;
      const filename = match?.[1] ? decodeURIComponent(match[1]) : t('admin.instanceFormData.exportFileName');
      downloadBlob(res.data as Blob, filename);
      message.success(t('admin.instanceFormData.exportSuccess'));
    } catch (e: any) {
      message.error(e?.msg || t('admin.instanceFormData.exportFailed'));
    } finally {
      setExporting(false);
    }
  };

  const columns: TableColumnsType<any> = useMemo(
    () => [
      { title: t('admin.table.processType'), dataIndex: 'defineName', key: 'defineName', width: 140, ellipsis: true },
      { title: t('admin.table.title'), dataIndex: 'title', key: 'title', width: 180, ellipsis: true },
      { title: t('admin.table.serialNo'), dataIndex: 'instId', key: 'instId', width: 170, ellipsis: true },
      ...dynamicFields.map((field) => ({
        title: field.name || field.key,
        dataIndex: field.key,
        key: field.key,
        width: 160,
        ellipsis: !['image', 'imageArray', 'fileArray'].includes(String(field.valueType)),
        render: (_: unknown, record: any) => {
          const entry = (record.fieldData || []).find((item: any) => item.key === field.key);
          return renderFieldValue(t, entry?.value, entry?.valueType ?? field.valueType, entry?.type ?? field.type);
        },
      })),
      {
        title: t('admin.table.initiator'),
        dataIndex: 'initiator',
        key: 'initiator',
        width: 150,
        render: (_: unknown, record: any) => (
          <WAvatar
            id={record.initiator?.id}
            name={record.initiator?.name}
            src={record.initiator?.avatar}
            status="agent"
            showStatus={record.isAgent}
            size={24}
          />
        ),
      },
      { title: t('admin.table.initiatorDept'), dataIndex: 'deptName', key: 'deptName', width: 120, ellipsis: true },
      { title: t('admin.table.currentNode'), dataIndex: 'currentNodeName', key: 'currentNodeName', width: 120, ellipsis: true },
      {
        title: t('admin.table.status'),
        dataIndex: 'status',
        key: 'status',
        width: 100,
        render: (value: string) => statusTag(t, value),
      },
      { title: t('admin.table.submitTime'), dataIndex: 'createTime', key: 'createTime', width: 170 },
      {
        title: t('admin.table.endTime'),
        dataIndex: 'endTime',
        key: 'endTime',
        width: 170,
        render: (time?: string | null) => time || '-',
      },
      {
        title: t('admin.table.action'),
        key: 'action',
        width: 110,
        fixed: 'right',
        render: (_: unknown, record: any) =>
          record.fieldData?.length ? (
            <Button type="link" size="small" icon={<EyeOutlined />} onClick={() => setDetailRecord(record)}>
              {t('admin.table.fieldDetail')}
            </Button>
          ) : (
            '-'
          ),
      },
    ],
    [dynamicFields, t]
  );

  return (
    <div>
      <Card size="small" style={{ marginBottom: 12 }}>
        <Space wrap>
          <Input
            placeholder={t('admin.instanceFormData.searchFormName')}
            prefix={<SearchOutlined />}
            value={modelKeyword}
            onChange={(event) => setModelKeyword(event.target.value)}
            allowClear
            style={{ width: 180 }}
          />
          <Cascader
            placeholder={t('admin.table.processType')}
            options={cascaderOptions}
            value={codePath}
            onChange={(value) => void handleCodeChange(value as string[] | undefined)}
            displayRender={(labels) => labels[labels.length - 1]}
            showSearch
            allowClear
            style={{ width: 220 }}
          />
          <Select
            placeholder={t('admin.instanceFormData.processStatus')}
            options={statusOptions}
            value={status}
            onChange={(value) => setStatus(value)}
            allowClear
            style={{ width: 120 }}
          />
          <DatePicker.RangePicker
            showTime
            format="YYYY-MM-DD HH:mm"
            value={startRange}
            onChange={(value) => setStartRange(value as [Dayjs, Dayjs] | null)}
            placeholder={[t('admin.instanceFormData.submitTimeStart'), t('admin.instanceFormData.submitTimeEnd')]}
            style={{ width: 330 }}
          />
          <Space.Compact>
            <Select
              placeholder={t('admin.instanceFormData.selectField')}
              options={fieldOptions}
              value={fieldKey}
              onChange={(value) => setFieldKey(value)}
              allowClear
              showSearch
              optionFilterProp="label"
              style={{ width: 150 }}
            />
            <Select
              placeholder={t('admin.instanceFormData.compareRelation')}
              options={compareOptions}
              value={compare}
              onChange={(value) => setCompare(value)}
              style={{ width: 110 }}
            />
            <Input
              placeholder={t('admin.instanceFormData.inputValue')}
              value={fieldValue}
              onChange={(event) => setFieldValue(event.target.value)}
              onPressEnter={handleSearch}
              allowClear
              style={{ width: 180 }}
            />
          </Space.Compact>
          <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
            {t('common.search')}
          </Button>
          <Button icon={<ReloadOutlined />} onClick={handleReset}>
            {t('common.reset')}
          </Button>
          <Button
            icon={<DownloadOutlined />}
            loading={exporting}
            disabled={!code}
            onClick={() => void handleExport()}
          >
            {t('admin.instanceFormData.exportData')}
          </Button>
        </Space>
      </Card>

      <Table
        rowKey="instId"
        loading={loading}
        dataSource={records}
        columns={columns}
        scroll={{ x: 'max-content' }}
        locale={{ emptyText: code ? undefined : t('admin.instanceFormData.emptySelectType') }}
        pagination={{
          current: pageNo,
          pageSize,
          total,
          showSizeChanger: true,
          pageSizeOptions: [10, 20, 50, 100],
          showTotal: (value) => t('admin.common.totalData').replace('{total}', String(value)),
          onChange: (page, size) => {
            setPageNo(page);
            setPageSize(size);
          },
        }}
      />

      <Modal
        title={
          <span>
            {t('admin.table.fieldDetail')}
            {detailRecord?.title ? ` - ${detailRecord.title}` : detailRecord?.instId ? ` - ${detailRecord.instId}` : ''}
          </span>
        }
        open={Boolean(detailRecord)}
        width={860}
        footer={null}
        onCancel={() => setDetailRecord(null)}
        destroyOnHidden
      >
        <Table
          rowKey="key"
          size="small"
          pagination={false}
          dataSource={detailRecord?.fieldData || []}
          scroll={{ x: 'max-content' }}
          columns={[
            { title: t('admin.table.fieldKey'), dataIndex: 'key', key: 'key', width: 170 },
            { title: t('admin.table.fieldName'), dataIndex: 'name', key: 'name', width: 170 },
            {
              title: t('admin.table.valueType'),
              dataIndex: 'valueType',
              key: 'valueType',
              width: 130,
              render: (value: string) => <Tag color="cyan">{value}</Tag>,
            },
            {
              title: t('admin.table.fieldValue'),
              key: 'value',
              render: (_: unknown, field: any) => renderFieldValue(t, field.value, field.valueType, field.type),
            },
          ]}
        />
        <Typography.Text type="secondary" style={{ display: 'block', marginTop: 8 }}>
          {t('admin.common.totalFields').replace('{total}', String(detailRecord?.fieldData?.length || 0))}
        </Typography.Text>
      </Modal>
    </div>
  );
};

export default InstanceFormDataManager;
