// apps/web/src/views/wflow/pages/admin/ModelManager.vue
<script setup>
import {
  copyModel,
  createProcGroup, deleteModel,
  delProcGroup, enableModel, getProcActiveModel,
  getProcGroupItems, saveModel, updateGroupModelSort,
  updateGroupName,
  updateGroupSort
} from "@/api/model.js";
import {VueDraggable} from "vue-draggable-plus";
import {ElMessage, ElMessageBox} from "element-plus";
import {$debounce, getResPrefix, isEmpty} from "@/utils/GlobalFunc.js";
import {exportText} from "@/utils/ProcessUtil.js";

const search = ref()
const fileInput = ref()
const inputGroup = ref()
const loading = ref(false)
const modelGroupList = ref([])
const startSort = ref(false)
const dataGroups = ref([])

//const doSearch = $debounce(getModelGroupList, 1000)
const dragDisable = computed(() => !isEmpty(search.value))

onMounted(() => getModelGroupList())
const _loadDataGroups = $debounce(loadDataGroups, 800)

function loadDataGroups() {
  if (isEmpty(search.value)){
    dataGroups.value = modelGroupList.value
  } else {
    dataGroups.value = modelGroupList.value.map(obj => {
      const filteredItems = obj.items.filter(item =>
          item.procName.includes(search.value)
      );
      return { ...obj, items: filteredItems };
    }).filter(obj => obj.items.length > 0);
  }
}

function getModelGroupList() {
  loading.value = true
  getProcGroupItems().then(res => {
    loading.value = false
    modelGroupList.value = res.data.map(group => {
      group.items.forEach(v => {
        v.logo = JSON.parse(v.logo)
        v.startupPerm = JSON.parse(v.startupPerm)
        v.startupPerm = resolveStartupPerm(v)
        v.adminPerm = resolveAdminPerm(v)
      })
      return group
    })
    dataGroups.value = modelGroupList.value
    _loadDataGroups()
  }).catch(err => loading.value = false)
}

function importProcJson(group) {
  inputGroup.value = group.id
  fileInput.value.click()
}

function addOrEditGroup(group) {
  ElMessageBox.prompt('请输入分组名称并提交', '提示', {
    confirmButtonText: '确认',
    cancelButtonText: '取消',
    inputPattern: /^[\s\S]{2,30}$/,
    inputValue: group.name,
    inputPlaceholder: "请输入分组名称",
    inputErrorMessage: '字符长度为2~30',
  }).then(({value}) => {
    (group.id ? updateGroupName(group.id, value) : createProcGroup(value)).then(res => {
      ElMessage.success(res.data)
      getModelGroupList()
    }).catch(err => ElMessage.error(err.msg))
  })
}

function doGroupSort(){
  loading.value = true
  updateGroupSort(dataGroups.value.map(v => v.id)).then(res => {
    getModelGroupList()
    ElMessage.success(res.data)
  }).catch(err => {
    loading.value = false
    ElMessage.error(err.msg)
  })
}

function groupSort(){
  startSort.value = !startSort.value
  if (!startSort.value){
    doGroupSort()
  }
}

function delGroup(group) {
  ElMessageBox.confirm('您确认要删除该分组吗', '提示', {
    confirmButtonText: '确认',
    cancelButtonText: '取消'
  }).then(() => {
    loading.value = true
    delProcGroup(group.id).then(res => {
      getModelGroupList()
      ElMessage.success(res.data)
    }).catch(err => {
      loading.value = false
      ElMessage.error(err.msg)
    })
  })
}

function designModel(code, groupId) {
  sessionStorage.removeItem('designCode')
  const prefix = getResPrefix()
  if (code){
    //编辑已有流程
    window.open(`${prefix}/designer?code=${code}`, '_blank')
  } else {
    //新增指定分组
    window.open(`${prefix}/designer?${groupId ? 'groupId=' + groupId : ''}`, '_blank')
  }
}

function activeModel(model) {
  const action = model.status === 1 ? '停用':'启用'
  ElMessageBox.confirm(`您确认要${action} [${model.procName}] 吗？`, '提示', {
    confirmButtonText: '确认',
    cancelButtonText: '取消',
    type: 'warning',
  }).then(() => {
    enableModel(model.status !== 1, model.code).then(res => {
      ElMessage.success(res.data)
      getModelGroupList()
    }).catch(err => {
      ElMessage.error(err.msg)
    })
  })
}

function delProcModel(model) {
  ElMessageBox.prompt(`删除该流程将会连带删除系统内所有相关数据，如果您已知晓该风险需要继续操作
  ，请输入验证语 [删除${model.procName}]`, '风险操作二次确认', {
    confirmButtonText: '确认删除',
    cancelButtonText: '我再想想',
    type: "warning",
    inputValidator: v => {
      if(v !== `删除${model.procName}`) return '请正确输入提示语'
      return true
    },
    inputPlaceholder: `输入： 删除${model.procName}`
  }).then(({value}) => {
    deleteModel(model.code).then(res => {
      ElMessage.success(res.data)
      getModelGroupList()
    }).catch(err => {
      ElMessage.error(err.msg)
    })
  })
}

//解析发起权限描述
function resolveStartupPerm(model) {
  const desc = '全员'
  switch (model.startupRange) {
    case "RANGE":
      return model.startupPerm.map(v => v.name).join('、') || desc
    case "NONE":
      return '全员禁止'
    default:
      return desc
  }
}

function resolveAdminPerm(model) {
  const rules = JSON.parse(model.adminPerm || '[]')
  return rules.map(v => v.name).join('、')
}

function copy(model) {
  ElMessageBox.prompt('请输入新的模型名称', '复制模型', {
    type: 'info',
    confirmButtonText: '确认',
    cancelButtonText: '取消',
    inputPattern: /^[\s\S]{2,30}$/,
    inputPlaceholder: "请输入模型名称",
    inputErrorMessage: '字符长度为2~30',
  }).then(({value}) => {
    copyModel(model.code, value).then(res => {
      ElMessage.success(res.data)
      getModelGroupList()
    }).catch(err => {
      ElMessage.error(err.msg || err)
    })
  })
}

function sortEnd(group) {
  updateGroupModelSort(group.id, group.items.map(v => v.code)).then(res => {
    ElMessage.success("排序成功")
  }).catch(err => {
    ElMessage.error(err.msg || err)
  })
}

function exportProcModel(app) {
  getProcActiveModel(app.code).then(res => {
    res.data.defineId = null
    res.data.deployId = null
    res.data.version = 1
    exportText(JSON.stringify(res.data), `${res.data.procName}-v${app.version}.json`)
  })
}

function configOnload(event) {
  const file = event.target.files[0];
  const reader = new FileReader();
  reader.onload = (e) => {
    try {
      const jsonData = JSON.parse(e.target.result);
      //清除code，新增数据
      jsonData.code = null
      jsonData.id = null
      jsonData.groupId = inputGroup.value
      saveModel(jsonData).then(() => {
        fileInput.value.value = null
        ElMessage.success("导入流程成功")
        getModelGroupList()
      }).catch(err => {
        ElMessage.error(err.msg)
      })
    } catch (error) {
      ElMessage.warning("解析流程json文件失败")
    }
  };
  reader.readAsText(file);
}

watch(search, _loadDataGroups)
</script>

<template>
  <div v-loading="loading">
    <input style="display: none" @change="configOnload" type="file" ref="fileInput" accept=".json">
    <div class="w-pm-header">
      <el-input style="width: 250px;" clearable v-model.trim="search" prefix-icon="search"
                :placeholder="$t('design.modelMg.search')"/>
      <div>
        <el-button :icon="startSort ? 'Finished' : 'Sort'" :type="startSort ? 'warning' : 'default'"
                   @click="groupSort" :disabled="dragDisable">
          {{ startSort ? $t('design.modelMg.endSort') : $t('design.modelMg.sort') }}
        </el-button>
        <el-button icon="plus" type="primary" @click="designModel()">{{ $t('design.modelMg.newModel') }}</el-button>
        <el-button icon="plus" @click="addOrEditGroup">{{ $t('design.modelMg.newGroup') }}</el-button>
      </div>
    </div>
    <el-empty v-if="dataGroups.length === 0"></el-empty>
    <vue-draggable class="w-pm-groups" v-model="dataGroups" :animation="150" :disabled="!startSort || dragDisable"
                   handle=".w-pm-drag" v-else>
      <div class="w-card" :style="{padding: startSort ? '0 20px':'0 20px 20px 20px'}" :key="group.id"
           v-for="group in dataGroups">
        <div class="w-pm-group-header">
          <iconify v-if="startSort" style="margin-right: 10px; cursor: grab" class="w-pm-drag" icon="ci:drag-vertical"/>
          <el-text style="flex: 1" size="large">{{ group.name }}</el-text>
          <div>
            <el-button link icon="BottomRight" @click="importProcJson(group)">导入</el-button>
            <el-button link icon="edit" @click="addOrEditGroup(group)">编辑</el-button>
            <el-button link icon="delete" @click="delGroup(group)">删除</el-button>
          </div>
        </div>
        <div v-show="!startSort">
          <div class="w-pm-group-empty" v-if="group.items.length === 0">
            <el-button type="primary" icon="plus" text @click="designModel(null, group.id)">{{ $t('design.modelMg.newModel') }}</el-button>
          </div>
          <vue-draggable v-else class="w-pm-group-content" :disabled="dragDisable" handle=".w-pm-drag" v-model="group.items" :animation="150" @end="sortEnd(group)">
            <el-row :class="{'w-pm-group-app': true, 'w-pm-disable': app.status !== 1}" v-for="app in group.items">
              <el-col :span="6" class="w-flex-col-ct">
                <div class="w-pm-drag">
                  <iconify icon="ci:drag-vertical"/>
                </div>
                <div>
                  <iconify class="w-process-icon" color="#ffffff" :style="{background: app.logo.bgc}" :icon="app.logo.name"/>
                </div>
                <div style="width: calc(100% - 80px);">
                  <el-text class="w-app-name" truncated>{{ app.procName }}</el-text>
                  <el-text style="display: block; color: var(--el-text-color-secondary)" size="small" truncated>
                    {{ app.remark }}
                  </el-text>
                </div>

              </el-col>
              <el-col :span="2">
                <el-badge is-dot :hidden="!app.hasNewVersion">
                  <el-tag :type="!app.defineId || app.status !== 1 ? 'info' : 'primary'" size="small">v{{app.version}}</el-tag>
                </el-badge>

              </el-col>
              <el-col :span="9">
                <el-text style="display: block" truncated size="small">{{ $t('design.modelMg.update') }}: {{ app.updateTime }}</el-text>
                <el-text truncated size="small">{{ $t('design.modelMg.range') }}: {{app.startupPerm}}</el-text>
              </el-col>
              <el-col :span="6" class="w-flex-col-ct">
                <template v-if="app.hasManagePerm">
                  <el-button link icon="edit" type="primary" @click="designModel(app.code)">{{ $t('design.modelMg.edit') }}
                  </el-button>
                  <el-button link :icon="app.status === 1 ? 'Remove' : 'CircleCheck'" :type="app.status === 1 ? 'warning' : 'primary'" @click="activeModel(app)">
                    {{ $t(`design.modelMg.${app.status === 1 ? 'disable' : 'enable'}`) }}
                  </el-button>
                  <el-dropdown>
                    <el-button style="margin-left: 5px" link icon="more">更多</el-button>
                    <template #dropdown>
                      <el-dropdown-menu>
                        <el-dropdown-item @click="copy(app)">
                          <el-icon><CopyDocument/></el-icon>
                          {{ $t('design.modelMg.copy') }}
                        </el-dropdown-item>
                        <el-dropdown-item @click="exportProcModel(app)">
                          <el-icon><TopLeft/></el-icon>
                          {{ $t('design.modelMg.export') }}
                        </el-dropdown-item>
                        <el-dropdown-item @click="delProcModel(app)">
                          <el-icon><Delete/></el-icon>
                          {{ $t('design.modelMg.del') }}
                        </el-dropdown-item>
                      </el-dropdown-menu>
                    </template>
                  </el-dropdown>
                </template>
               <div class="w-flex-col-ct" style="width: 100%;" v-else>
                 <el-button link icon="TopLeft" @click="exportProcModel(app)">
                   {{ $t('design.modelMg.export') }}
                 </el-button>
                 <el-divider direction="vertical"/>
                 <el-text truncated line-clamp="2">仅[{{ app.adminPerm }}]可编辑</el-text>
               </div>
              </el-col>
            </el-row>
          </vue-draggable>
        </div>
      </div>
    </vue-draggable>
  </div>

</template>

<style scoped lang="less">
.w-pm-header {
  display: flex;
  justify-content: space-between;
}

.w-pm-disable {
  background-color: var(--el-fill-color-light) !important;
}

.w-pm-groups {

  & > div {
    padding-top: 0;
    margin: 10px 0;
  }

  .w-pm-group-empty {
    width: 100%;
    display: flex;
    justify-content: center;
  }

  .w-pm-group-header {
    padding: 10px 0;
    display: flex;
    align-items: center;
  }

  .w-pm-group-content {
    padding: 2px;
    border-radius: 5px;
    background-color: var(--el-bg-color-page);

    .w-pm-group-app {
      margin-top: 2px;
      padding: 8px;
      display: flex;
      justify-content: space-between;
      border-radius: 5px;
      align-items: center;
      background-color: var(--el-bg-color);

      .w-app-name {

      }

      .w-pm-drag {
        cursor: grab;
      }
      .w-process-icon {
        margin: 0 10px;
      }
    }

    .w-pm-group-app:first-child {
      margin-top: 0;
    }
  }
}
</style>

// apps/web-react/src/views/admin/ModelManager.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Card,
  Button,
  Space,
  Tag,
  Typography,
  Row,
  Col,
  Modal,
  Input,
  message,
  Popconfirm,
  Spin,
  Empty,
  Badge,
  Tooltip,
} from 'antd';
import {
  PlusOutlined,
  EditOutlined,
  CopyOutlined,
  DeleteOutlined,
  AppstoreOutlined,
  SearchOutlined,
  ImportOutlined,
  ExportOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
} from '@ant-design/icons';
import {
  getProcGroupItems,
  createProcGroup,
  delProcGroup,
  enableModel,
  deleteModel,
  copyModel,
  updateGroupName,
  updateGroupSort,
  updateGroupModelSort,
  getProcActiveModel,
  saveModel,
} from '@/api/model';
import { NodeTypes } from '@/views/process/ProcessNodes';
import { useTranslation } from '@/i18n';
import { exportText } from '@/utils/ProcessUtil';
import {
  defaultModelPayload,
  parseJson,
  resolveAdminLabel,
  resolveStartupLabel,
  sanitizeModelForTransfer,
  type ModelLogo,
} from '@/components/modelDefaults';

interface ModelItem {
  code: string;
  name?: string;
  procName?: string;
  version?: number;
  status?: number;
  hasNewVersion?: boolean;
  hasManagePerm?: boolean;
  updateTime?: string;
  remark?: string;
  logo?: string;
  startupRange?: string;
  startupPerm?: string;
  adminPerm?: string;
  defineId?: string;
}

interface GroupItem {
  id: string;
  name: string;
  sort?: number;
  items: ModelItem[];
}

const DEFAULT_LOGO: ModelLogo = { name: 'file-icons:omnigraffle', bgc: '#4C87F3', color: '#FFFFFF' };

export const ModelManager: React.FC = () => {
  const navigate = useNavigate();
  const { t } = useTranslation();
  const [loading, setLoading] = useState(false);
  const [groups, setGroups] = useState<GroupItem[]>([]);
  const [search, setSearch] = useState('');

  const fileInputRef = useRef<HTMLInputElement>(null);
  const importGroupRef = useRef('');

  const [groupModalOpen, setGroupModalOpen] = useState(false);
  const [groupModalId, setGroupModalId] = useState('');
  const [groupName, setGroupName] = useState('');

  const [copyModalOpen, setCopyModalOpen] = useState(false);
  const [copyCode, setCopyCode] = useState('');
  const [copyName, setCopyName] = useState('');

  useEffect(() => {
    void loadList();
  }, []);

  const loadList = async () => {
    setLoading(true);
    try {
      const res = await getProcGroupItems();
      const list = Array.isArray(res.data) ? res.data : [];
      setGroups(
        list.map((group: any) => ({
          ...group,
          items: Array.isArray(group.items) ? group.items : [],
        }))
      );
    } catch (e: any) {
      message.error(e?.msg || t('admin.modelManager.fetchFailed'));
    } finally {
      setLoading(false);
    }
  };

  const dataGroups = useMemo(() => {
    const term = search.trim();
    if (!term) return groups;
    return groups
      .map((group) => ({
        ...group,
        items: group.items.filter((item) => (item.procName || item.name || '').includes(term)),
      }))
      .filter((group) => group.items.length > 0);
  }, [groups, search]);

  const sortDisabled = search.trim() !== '';

  const getLogo = (item: ModelItem): ModelLogo => parseJson<ModelLogo>(item.logo, DEFAULT_LOGO);

  const openCreateGroup = () => {
    setGroupModalId('');
    setGroupName('');
    setGroupModalOpen(true);
  };

  const openRenameGroup = (group: GroupItem) => {
    setGroupModalId(group.id);
    setGroupName(group.name);
    setGroupModalOpen(true);
  };

  const handleSaveGroup = async () => {
    const name = groupName.trim();
    if (name.length < 2 || name.length > 30) {
      message.warning(t('admin.modelManager.nameLength'));
      return;
    }
    try {
      if (groupModalId) await updateGroupName(groupModalId, name);
      else await createProcGroup(name);
      message.success(
        groupModalId ? t('admin.modelManager.groupUpdated') : t('admin.modelManager.groupCreated')
      );
      setGroupModalOpen(false);
      await loadList();
    } catch (e: any) {
      message.error(e?.msg || t('common.failed'));
    }
  };

  const handleDeleteGroup = async (groupId: string) => {
    try {
      const res = await delProcGroup(groupId);
      message.success(res.data || t('admin.modelManager.groupDeleted'));
      await loadList();
    } catch (e: any) {
      message.error(e?.msg || t('admin.modelManager.deleteGroupFailed'));
    }
  };

  const handleGroupSort = async (index: number, direction: -1 | 1) => {
    const target = index + direction;
    if (target < 0 || target >= groups.length) return;
    const next = [...groups];
    [next[index], next[target]] = [next[target], next[index]];
    setGroups(next);
    try {
      const res = await updateGroupSort(next.map((group) => group.id));
      message.success(res.data || t('admin.modelManager.sortSuccess'));
    } catch (e: any) {
      message.error(e?.msg || t('admin.modelManager.sortFailed'));
    }
    await loadList();
  };

  const handleModelSort = async (group: GroupItem, index: number, direction: -1 | 1) => {
    const target = index + direction;
    if (target < 0 || target >= group.items.length) return;
    const next = [...group.items];
    [next[index], next[target]] = [next[target], next[index]];
    try {
      const res = await updateGroupModelSort(
        group.id,
        next.map((item) => item.code)
      );
      message.success(res.data || t('admin.modelManager.sortSuccess'));
    } catch (e: any) {
      message.error(e?.msg || t('admin.modelManager.sortFailed'));
    }
    await loadList();
  };

  const handleCreateModel = async (targetGroupId?: string) => {
    try {
      let groupId = targetGroupId || groups[0]?.id || '';
      if (!groupId) {
        const created = await createProcGroup(t('admin.modelManager.defaultGroup'));
        groupId = created.data;
      }
      const code = `proc-${crypto.randomUUID()}`;
      const sort = (groups.find((group) => group.id === groupId)?.items?.length || 0) + 1;
      await saveModel(
        defaultModelPayload({
          code,
          procName: t('admin.common.untitledProcess'),
          groupId,
          sort,
          process: NodeTypes.Start.create(),
        })
      );
      message.success(t('admin.modelManager.createSuccess'));
      window.open(`/designer?code=${encodeURIComponent(code)}`, '_blank');
      await loadList();
    } catch (e: any) {
      message.error(e?.msg || t('admin.modelManager.createFailed'));
    }
  };

  const handleToggleEnable = (item: ModelItem) => {
    const enable = item.status !== 1;
    Modal.confirm({
      title: t('common.tip'),
      content: t('admin.modelManager.toggleConfirm')
        .replace('{action}', enable ? t('design.modelMg.enable') : t('design.modelMg.disable'))
        .replace('{name}', item.procName || item.name || ''),
      okText: t('common.confirm'),
      cancelText: t('common.cancel'),
      onOk: async () => {
        try {
          const res = await enableModel(enable, item.code);
          message.success(res.data || (enable ? t('admin.modelManager.enableSuccess') : t('admin.modelManager.disableSuccess')));
          await loadList();
        } catch (e: any) {
          message.error(e?.msg || t('common.failed'));
        }
      },
    });
  };

  const handleDeleteModel = async (code: string) => {
    try {
      const res = await deleteModel(code);
      message.success(res.data || t('admin.common.deleteSuccess'));
      await loadList();
    } catch (e: any) {
      message.error(e?.msg || t('admin.common.deleteFailed'));
    }
  };

  const handleOpenCopy = (item: ModelItem) => {
    setCopyCode(item.code);
    setCopyName(`${item.procName || item.name} ${t('admin.modelManager.copySuffix')}`);
    setCopyModalOpen(true);
  };

  const handleConfirmCopy = async () => {
    if (!copyName.trim()) {
      message.warning(t('admin.modelManager.copyNameRequired'));
      return;
    }
    try {
      const res = await copyModel(copyCode, copyName.trim());
      message.success(res.data || t('admin.modelManager.copySuccess'));
      setCopyModalOpen(false);
      await loadList();
    } catch (e: any) {
      message.error(e?.msg || t('admin.modelManager.copyFailed'));
    }
  };

  const handleImportClick = (groupId: string) => {
    importGroupRef.current = groupId;
    fileInputRef.current?.click();
  };

  const handleImportFile = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    event.target.value = '';
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (evt) => {
      try {
        const parsed = JSON.parse(String(evt.target?.result || ''));
        const payload = sanitizeModelForTransfer(parsed);
        payload.code = null;
        payload.id = null;
        payload.groupId = importGroupRef.current;
        await saveModel(payload);
        message.success(t('admin.modelManager.importSuccess'));
        await loadList();
      } catch (e: any) {
        message.warning(e?.msg || t('admin.modelManager.importFailed'));
      }
    };
    reader.readAsText(file);
  };

  const handleExport = async (item: ModelItem) => {
    try {
      const res = await getProcActiveModel(item.code);
      exportText(
        JSON.stringify(sanitizeModelForTransfer(res.data)),
        `${item.procName || item.name || item.code}-v${item.version || 1}.json`
      );
    } catch (e: any) {
      message.error(e?.msg || t('admin.modelManager.exportFailed'));
    }
  };

  const renderModel = (group: GroupItem, item: ModelItem, index: number) => {
    const modelLogo = getLogo(item);
    const active = item.status === 1;
    const manage = Boolean(item.hasManagePerm);
    const adminLabel = resolveAdminLabel(item) || t('admin.modelManager.adminFallback');

    return (
      <Col span={8} key={item.code}>
        <Card
          size="small"
          hoverable
          style={{ borderRadius: 8, opacity: active ? 1 : 0.75 }}
          styles={{ body: { padding: 12 } }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8 }}>
            <div
              title={modelLogo.name}
              style={{
                width: 36,
                height: 36,
                borderRadius: 6,
                background: modelLogo.bgc,
                color: modelLogo.color,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
              }}
            >
              <AppstoreOutlined style={{ fontSize: 18 }} />
            </div>
            <div style={{ flex: 1, overflow: 'hidden' }}>
              <Typography.Text strong ellipsis style={{ display: 'block' }}>
                {item.procName || item.name}
              </Typography.Text>
              <Space size={4} wrap>
                <Badge dot={Boolean(item.hasNewVersion)}>
                  <Tag style={{ fontSize: 11 }} color={active ? 'blue' : 'default'}>
                    v{item.version || 1}
                  </Tag>
                </Badge>
                <Tag color={active ? 'success' : 'default'} style={{ fontSize: 11 }}>
                  {active ? t('admin.status.enabled') : t('admin.status.disabled')}
                </Tag>
              </Space>
            </div>
            {!sortDisabled && manage && (
              <Space size={0} direction="vertical">
                <Button
                  type="text"
                  size="small"
                  icon={<ArrowUpOutlined />}
                  disabled={index === 0}
                  onClick={() => handleModelSort(group, index, -1)}
                />
                <Button
                  type="text"
                  size="small"
                  icon={<ArrowDownOutlined />}
                  disabled={index === group.items.length - 1}
                  onClick={() => handleModelSort(group, index, 1)}
                />
              </Space>
            )}
          </div>

          <div style={{ fontSize: 12, color: '#888', minHeight: 20 }}>{item.remark || t('admin.modelManager.noDescription')}</div>
          <div style={{ fontSize: 12, color: '#888' }}>{t('admin.modelManager.updated')}: {item.updateTime || '-'}</div>
          <div style={{ fontSize: 12, color: '#888' }}>{t('admin.modelManager.startupRange')}: {resolveStartupLabel(item)}</div>

          <div style={{ marginTop: 8, display: 'flex', flexWrap: 'wrap', gap: 4 }}>
            {manage ? (
              <>
                <Button type="link" size="small" icon={<EditOutlined />} onClick={() => navigate(`/designer?code=${item.code}`)}>
                  {t('admin.modelManager.design')}
                </Button>
                <Button type="link" size="small" onClick={() => handleToggleEnable(item)}>
                  {active ? t('design.modelMg.disable') : t('design.modelMg.enable')}
                </Button>
                <Button type="link" size="small" icon={<CopyOutlined />} onClick={() => handleOpenCopy(item)}>
                  {t('design.modelMg.copy')}
                </Button>
                <Button type="link" size="small" icon={<ExportOutlined />} onClick={() => handleExport(item)}>
                  {t('design.modelMg.export')}
                </Button>
                <Popconfirm
                  title={t('admin.modelManager.deleteModelConfirm')}
                  okText={t('admin.modelManager.confirmDelete')}
                  cancelText={t('admin.modelManager.thinkAgain')}
                  onConfirm={() => handleDeleteModel(item.code)}
                >
                  <Button type="link" size="small" danger icon={<DeleteOutlined />}>
                    {t('design.modelMg.del')}
                  </Button>
                </Popconfirm>
              </>
            ) : (
              <>
                <Button type="link" size="small" icon={<ExportOutlined />} onClick={() => handleExport(item)}>
                  {t('design.modelMg.export')}
                </Button>
                <Tooltip title={t('admin.modelManager.onlyAdminEdit').replace('{admin}', adminLabel)}>
                  <Typography.Text type="secondary" ellipsis style={{ fontSize: 12, maxWidth: 160 }}>
                    {t('admin.modelManager.onlyAdminEdit').replace('{admin}', adminLabel)}
                  </Typography.Text>
                </Tooltip>
              </>
            )}
          </div>
        </Card>
      </Col>
    );
  };

  return (
    <div>
      <input ref={fileInputRef} type="file" accept=".json" style={{ display: 'none' }} onChange={handleImportFile} />

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
        <Typography.Title level={4} style={{ margin: 0 }}>
          {t('admin.modelManager.title')}
        </Typography.Title>
        <Space>
          <Input
            allowClear
            prefix={<SearchOutlined />}
            placeholder={t('design.modelMg.search')}
            style={{ width: 220 }}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <Button icon={<PlusOutlined />} onClick={openCreateGroup}>
            {t('design.modelMg.newGroup')}
          </Button>
          <Button type="primary" icon={<PlusOutlined />} onClick={() => handleCreateModel()}>
            {t('design.modelMg.newModel')}
          </Button>
        </Space>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: 80 }}>
          <Spin size="large" />
        </div>
      ) : dataGroups.length === 0 ? (
        <Empty description={search ? t('admin.modelManager.searchEmpty') : t('admin.modelManager.empty')} />
      ) : (
        dataGroups.map((group, groupIndex) => (
          <div key={group.id} style={{ marginBottom: 28 }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
              <Space>
                <Typography.Text strong style={{ fontSize: 16 }}>
                  {group.name}
                </Typography.Text>
                <Tag>{t('admin.modelManager.processCount').replace('{count}', String(group.items.length))}</Tag>
                {!sortDisabled && (
                  <Space size={0}>
                    <Tooltip title={t('admin.modelManager.groupUp')}>
                      <Button
                        type="text"
                        size="small"
                        icon={<ArrowUpOutlined />}
                        disabled={groupIndex === 0}
                        onClick={() => handleGroupSort(groupIndex, -1)}
                      />
                    </Tooltip>
                    <Tooltip title={t('admin.modelManager.groupDown')}>
                      <Button
                        type="text"
                        size="small"
                        icon={<ArrowDownOutlined />}
                        disabled={groupIndex === dataGroups.length - 1}
                        onClick={() => handleGroupSort(groupIndex, 1)}
                      />
                    </Tooltip>
                  </Space>
                )}
              </Space>
              <Space>
                <Button size="small" type="link" icon={<ImportOutlined />} onClick={() => handleImportClick(group.id)}>
                  {t('admin.modelManager.import')}
                </Button>
                <Button size="small" type="link" icon={<EditOutlined />} onClick={() => openRenameGroup(group)}>
                  {t('common.edit')}
                </Button>
                <Popconfirm
                  title={t('admin.modelManager.deleteGroupConfirm')}
                  okText={t('admin.modelManager.confirmDelete')}
                  cancelText={t('common.cancel')}
                  onConfirm={() => handleDeleteGroup(group.id)}
                >
                  <Button size="small" type="link" danger>
                    {t('common.delete')}
                  </Button>
                </Popconfirm>
                <Button size="small" type="link" onClick={() => handleCreateModel(group.id)}>
                  {t('admin.modelManager.createInGroup')}
                </Button>
              </Space>
            </div>

            {group.items.length === 0 ? (
              <div style={{ textAlign: 'center', padding: 16 }}>
                <Button type="dashed" icon={<PlusOutlined />} onClick={() => handleCreateModel(group.id)}>
                  {t('design.modelMg.newModel')}
                </Button>
              </div>
            ) : (
              <Row gutter={[16, 16]}>{group.items.map((item, index) => renderModel(group, item, index))}</Row>
            )}
          </div>
        ))
      )}

      <Modal
        title={groupModalId ? t('admin.modelManager.editGroupTitle') : t('admin.modelManager.newGroupTitle')}
        open={groupModalOpen}
        onCancel={() => setGroupModalOpen(false)}
        onOk={handleSaveGroup}
        okText={t('common.confirm')}
        cancelText={t('common.cancel')}
      >
        <Input
          placeholder={t('admin.modelManager.groupNamePlaceholder')}
          value={groupName}
          maxLength={30}
          onChange={(e) => setGroupName(e.target.value)}
          onPressEnter={handleSaveGroup}
        />
      </Modal>

      <Modal
        title={t('admin.modelManager.copyTitle')}
        open={copyModalOpen}
        onCancel={() => setCopyModalOpen(false)}
        onOk={handleConfirmCopy}
        okText={t('common.confirm')}
        cancelText={t('common.cancel')}
      >
        <Input
          placeholder={t('admin.modelManager.copyPlaceholder')}
          value={copyName}
          maxLength={30}
          onChange={(e) => setCopyName(e.target.value)}
          onPressEnter={handleConfirmCopy}
        />
      </Modal>
    </div>
  );
};

export default ModelManager;
