// apps/web-react/src/components/SearchTools.tsx
import React, { useEffect, useState } from 'react';
import { Cascader, DatePicker, Input, Select, Space, Button, message } from 'antd';
import { SearchOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { getProcGroupItemsList } from '@/api/model';
import { t, useTranslation } from '@/i18n';
import { formatMessage } from '@/utils/i18n';

export interface SearchParams {
  code?: string;
  status?: string;
  action?: string;
  title?: string;
  startRange?: string;
}

interface SearchToolsProps {
  value: SearchParams;
  onChange: (value: SearchParams) => void;
  onSearch: () => void;
  showStatus?: boolean;
  showAction?: boolean;
  showType?: boolean;
  startDesc?: string;
  endDesc?: string;
}

const statusOption = (value: string, labelKey: string) => ({
  get label() {
    return t(labelKey);
  },
  value,
});

const actionOption = (value: string, labelKey: string) => ({
  get label() {
    return t(labelKey);
  },
  value,
});

export const STATUS_OPTIONS = [
  statusOption('RUNNING', 'workspace.status.running'),
  statusOption('SUSPEND', 'workspace.status.suspended'),
  statusOption('REFUSE', 'workspace.status.refused'),
  statusOption('REVOKED', 'workspace.status.revoked'),
  statusOption('PASS', 'workspace.status.passed'),
  statusOption('EXCEPTION', 'workspace.status.exception'),
];

export const ACTION_OPTIONS = [
  actionOption('complete', 'workspace.actionOption.complete'),
  actionOption('agree', 'workspace.actionOption.agree'),
  actionOption('reject', 'workspace.actionOption.reject'),
  actionOption('forward', 'workspace.actionOption.forward'),
  actionOption('fallback', 'workspace.actionOption.fallback'),
  actionOption('beforeAdd', 'workspace.actionOption.beforeAdd'),
  actionOption('afterAdd', 'workspace.actionOption.afterAdd'),
  actionOption('revoke', 'workspace.actionOption.revoke'),
  actionOption('revise', 'workspace.actionOption.revise'),
  actionOption('withdraw', 'workspace.actionOption.withdraw'),
];

const presetOption = (value: () => [dayjs.Dayjs, dayjs.Dayjs], labelKey: string) => ({
  get label() {
    return t(labelKey);
  },
  value,
});

const rangePresets = [
  presetOption(() => [dayjs().subtract(1, 'hour'), dayjs()] as [dayjs.Dayjs, dayjs.Dayjs], 'workspace.search.presetHour'),
  presetOption(() => [dayjs().subtract(1, 'day'), dayjs()] as [dayjs.Dayjs, dayjs.Dayjs], 'workspace.search.presetDay'),
  presetOption(() => [dayjs().subtract(7, 'day'), dayjs()] as [dayjs.Dayjs, dayjs.Dayjs], 'workspace.search.presetWeek'),
  presetOption(() => [dayjs().subtract(30, 'day'), dayjs()] as [dayjs.Dayjs, dayjs.Dayjs], 'workspace.search.presetMonth'),
  presetOption(() => [dayjs().subtract(90, 'day'), dayjs()] as [dayjs.Dayjs, dayjs.Dayjs], 'workspace.search.presetQuarter'),
];

export const SearchTools: React.FC<SearchToolsProps> = ({
  value,
  onChange,
  onSearch,
  showStatus = false,
  showAction = false,
  showType = true,
  startDesc = '',
  endDesc = '',
}) => {
  const { t: translate } = useTranslation();
  const [groups, setGroups] = useState<any[]>([]);
  const [range, setRange] = useState<[dayjs.Dayjs | null, dayjs.Dayjs | null] | null>(null);

  useEffect(() => {
    getProcGroupItemsList()
      .then((res) => {
        const options = (res.data || [])
          .filter((group: any) => group.items?.length)
          .map((group: any) => ({
            value: group.id,
            label: group.name,
            children: group.items.map((item: any) => ({ value: item.code, label: item.procName })),
          }));
        setGroups(options);
      })
      .catch((error: any) => message.error(error?.msg || translate('workspace.search.groupFailed')));
  }, []);

  const patch = (part: Partial<SearchParams>) => onChange({ ...value, ...part });

  const update = () => {
    const encoded = range?.[0] && range?.[1]
      ? `${range[0].format('YYYY-MM-DD HH:mm:ss')},${range[1].format('YYYY-MM-DD HH:mm:ss')}`
      : undefined;
    onChange({ ...value, startRange: encoded });
    onSearch();
  };

  return (
    <Space wrap className="w-card" style={{ width: 'calc(100% - 40px)' }}>
      {showType && (
        <Cascader
          allowClear
          changeOnSelect
          options={groups}
          placeholder={translate('workspace.search.processType')}
          value={value.code ? [value.code] : undefined}
          displayRender={(labels) => labels[labels.length - 1]}
          onChange={(next) => patch({ code: (next?.[next.length - 1] as string) || undefined })}
          style={{ width: 200 }}
        />
      )}
      {showStatus && (
        <Select
          allowClear
          placeholder={translate('workspace.search.processStatus')}
          options={STATUS_OPTIONS}
          value={value.status}
          onChange={(next) => patch({ status: next })}
          style={{ width: 120 }}
        />
      )}
      {showAction && (
        <Select
          allowClear
          placeholder={translate('workspace.search.handleType')}
          options={ACTION_OPTIONS}
          value={value.action}
          onChange={(next) => patch({ action: next })}
          style={{ width: 130 }}
        />
      )}
      <Input
        allowClear
        prefix={<SearchOutlined />}
        placeholder={translate('workspace.search.placeholder')}
        value={value.title}
        onChange={(event) => patch({ title: event.target.value })}
        onPressEnter={update}
        style={{ width: 250 }}
      />
      <DatePicker.RangePicker
        showTime
        allowClear
        presets={rangePresets}
        value={range as any}
        placeholder={[
          formatMessage(translate('workspace.search.rangeStart'), { desc: startDesc }),
          formatMessage(translate('workspace.search.rangeEnd'), { desc: endDesc }),
        ]}
        onChange={(next) => setRange(next as any)}
        style={{ width: 350 }}
      />
      <Button type="primary" icon={<SearchOutlined />} onClick={update}>
        {translate('workspace.search.query')}
      </Button>
    </Space>
  );
};

export default SearchTools;

// apps/web/src/views/wflow/pages/workspace/subs/SearchTools.vue
<script setup>
import {getProcGroupItemsList} from "@/api/model.js";
import {ElMessage} from "element-plus";

const props = defineProps({
  modelValue: {
    type: Object,
    default: () => {
      return {}
    }
  },
  showStatus: Boolean,
  showAction: Boolean,
  showType: {
    type: Boolean,
    default: true
  },
  excludeUser: {
    type: Boolean,
    default: false
  },
  startDesc: {
    type: String,
    default: ''
  },
  endDesc: {
    type: String,
    default: ''
  }
})

const _value = defineModel()

const groupItems = ref([])
const pickerOptions = [
  {
    text: '近一小时',
    value: () => {
      const end = new Date();
      const start = new Date();
      start.setTime(start.getTime() - 3600 * 1000);
      return [start, end]
    }
  },
  {
    text: '近一天',
    value: () => {
      const end = new Date();
      const start = new Date();
      start.setTime(start.getTime() - 3600 * 1000 * 24);
      return [start, end]
    }
  }, {
    text: '最近一周',
    value: () =>{
      const end = new Date();
      const start = new Date();
      start.setTime(start.getTime() - 3600 * 1000 * 24 * 7);
      return [start, end]
    }
  }, {
    text: '最近一个月',
    value: () => {
      const end = new Date();
      const start = new Date();
      start.setTime(start.getTime() - 3600 * 1000 * 24 * 30);
      return [start, end]
    }
  }, {
    text: '最近三个月',
    value: () => {
      const end = new Date();
      const start = new Date();
      start.setTime(start.getTime() - 3600 * 1000 * 24 * 90);
      return [start, end]
    }
  }
]

onMounted(() => {
  getProcGroupItemsList().then(res => {
    groupItems.value = res.data.filter(g => g.items.length > 0).map(group => {
      return {
        value: group.id,
        label: group.name,
        children: group.items.map(it => {
          return {
            value: it.code,
            label: it.procName,
          }
        })
      }
    })
  }).catch(err => {
    ElMessage.error(err.msg)
  })
})
</script>

<template>
  <el-space class="w-card" style="width: calc(100% - 40px);">
    <el-cascader v-if="showType" clearable :show-all-levels="false" :options="groupItems" :props="{emitPath: false}" placeholder="流程类型" v-model="_value.code"/>
    <el-select v-if="showStatus" clearable prefix-icon="Search" v-model="_value.status" style="width: 120px;" placeholder="流程状态">
      <el-option label="进行中" value="RUNNING"/>
      <el-option label="暂停中" value="SUSPEND"/>
      <el-option label="被驳回" value="REFUSE"/>
      <el-option label="已撤销" value="REVOKED"/>
      <el-option label="审批通过" value="PASS"/>
      <el-option label="流程异常" value="EXCEPTION"/>
    </el-select>
    <el-select v-if="showAction" clearable prefix-icon="Search" v-model="_value.action" style="width: 120px;" placeholder="处理类型">
      <el-option label="办理" value="complete"/>
      <el-option label="同意" value="agree"/>
      <el-option label="拒绝" value="reject"/>
      <el-option label="转交" value="forward"/>
      <el-option label="回退" value="fallback"/>
      <el-option label="前加签" value="beforeAdd"/>
      <el-option label="后加签" value="afterAdd"/>
      <el-option label="撤销" value="revoke"/>
      <el-option label="修改" value="revise"/>
      <el-option label="撤回" value="withdraw"/>
    </el-select>
    <el-input v-model="_value.title" clearable prefix-icon="Search" style="width: 250px;" :placeholder="`搜索 ${excludeUser ? '' : '发起人、'}流程类型`"></el-input>
    <el-date-picker v-model="_value.startRange" :shortcuts="pickerOptions" style="width: 350px;"
                    type="datetimerange" value-format="YYYY-MM-DD HH:mm:ss" clearable
                    :start-placeholder="`${startDesc}开始时间`" :end-placeholder="`${startDesc}结束时间`"/>
    <el-button type="primary" icon="Search" @click="$emit('search')">查询</el-button>
  </el-space>
</template>

<style scoped lang="less">

</style>
