// apps/web/src/views/wflow/pages/workspace/ProcAgentPage.vue
<template>
  <div>
    <el-space class="w-card-sm" style="width: calc(100% - 20px);">
      <w-bright-block show-icon type="primary" content="设置审批代理人，让其他人临时代替我们来处理流程"/>
      <el-button icon="Plus" type="primary" @click="addAgent()">新增代理规则</el-button>
      <el-button icon="Search" type="primary" @click="getAgentList()">查询</el-button>
    </el-space>
    <div class="w-card-sm" style="margin-top: 10px" v-loading="loading">
      <el-table :data="agentDataList.records" :cell-style="{padding: '5px 0'}" :header-cell-style="tbCellStyle">
        <el-table-column prop="target" label="代理人">
          <template #default="scope">
            <w-avatar :id="scope.row.target.id" :name="scope.row.target.name" :src="scope.row.target.avatar"/>
          </template>
        </el-table-column>
        <el-table-column show-overflow-tooltip prop="scope" label="代理的流程范围">
          <template #default="scope">
            {{getAgentRange(scope.row.scope)}}
          </template>
        </el-table-column>
        <el-table-column prop="status" label="状态">
          <template #default="scope">
            <el-tag :type="scope.row.statusType">{{scope.row.statusText}}</el-tag>
          </template>
        </el-table-column>
        <el-table-column show-overflow-tooltip prop="reason" label="代理原因"/>
        <el-table-column show-overflow-tooltip prop="timeRange" label="代理时间范围">
          <template #default="scope">
            {{scope.row.timeRange.join(' ~ ')}}
          </template>
        </el-table-column>
        <el-table-column width="200" label="操作">
          <template #default="scope">
            <el-button type="primary" icon="Edit" link @click="updateAgent(scope.row)">编辑</el-button>
            <el-button type="danger" icon="Delete" link @click="deleteAgent(scope.row.id)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
      <div style="margin-top: 20px; display: flex; justify-content: right">
        <el-pagination v-model:current-page="dataParams.pageNo"
                       v-model:page-size="dataParams.pageSize"
                       :page-sizes="[10, 20, 50, 100]"
                       :disabled="agentDataList.pages === 0"
                       layout="total, sizes, prev, pager, next"
                       :total="agentDataList.total" background
                       @size-change="getAgentList"
                       @current-change="getAgentList"/>
      </div>
    </div>
    <w-dialog v-model="agentDialog" width="650" title="代理规则设置" @ok="confirmAgent()">
      <el-form ref="formRef" label-width="80px" :model="agentData">
        <el-form-item :rules="{type: 'array', required: true, message: '请选择谁来代理我', trigger: 'change'}"
                      error="选择谁来代理我" prop="target" label="代理对象">
          <w-org-plus-picker v-model="agentData.target" type="user" :excludes="[loginUser]"
                             placeholder="谁来代理我" @change="formRef.validateField('target')"/>
        </el-form-item>
        <el-form-item :rules="{type: 'array', required: !agentData.isAll, message: '请选择代理范围'}"
                      prop="scope" label="代理范围">
          <div class="w-flex-col-ct" style="width: 100%;">
            <el-checkbox label="所有流程" v-model="agentData.isAll"
                         @change="v => agentData.scope = agentData.isAll ? null : v"/>
            <el-divider direction="vertical"/>
            <el-cascader clearable :show-all-levels="false" :options="groupItems"
                         :props="{emitPath: false, multiple: true}" placeholder="需要代理的流程"
                         v-if="!agentData.isAll" style="width: calc(100% - 100px)" v-model="agentData.scope"/>
            <w-bright-block v-else show-icon type="warning" content="将会覆盖有效范围内的其他流程设置"/>
          </div>
        </el-form-item>
        <el-form-item :rules="{type: 'array', required: true, message: '请设置代理时间段'}"
                      prop="timeRange" label="代理时间">
          <el-date-picker v-model="agentData.timeRange" type="datetimerange"
                          range-separator="至" value-format="YYYY-MM-DD HH:mm:ss"
                          start-placeholder="代理开始时间" :disabled-date="disableDate"
                          end-placeholder="代理结束时间"
          />
        </el-form-item>
        <el-form-item prop="reason" label="代理原因">
          <el-input v-model="agentData.reason" show-word-limit
                    maxlength="50" type="textarea" placeholder="请输入代理原因"/>
        </el-form-item>
      </el-form>
    </w-dialog>
  </div>
</template>

<script setup>
import WOrgPlusPicker from "../../common/WOrgPlusPicker.vue";
import WBrightBlock from "../../common/WBrightBlock.vue";
import WDialog from "../../common/WDialog.vue";
import {getProcGroupItemsList} from "@/api/model.js";
import {dayjs, ElMessage, ElMessageBox} from "element-plus";
import {addAgentRule, deleteAgentRule, getAgentRulePage, updateAgentRule} from "@/api/handover.js";
import WAvatar from "@/views/wflow/common/WAvatar.vue";
import {useWflowStore} from "@/stores/modules/wflow.js";
import {deepCopy} from "@/utils/GlobalFunc.js";

const {loginUser} = useWflowStore()

const tbCellStyle = {
  background: 'var(--el-fill-color-lighter)',
  padding: '10px 0',
}
let isAdd = true
const formRef = ref();
const loading = ref(false);
const agentDialog = ref(false);
const agentData = ref({
  target: [],
  reason: '',
  scope: [],
  isAll: true,
  timeRange: []
})
const now = new Date()
now.setHours(0, 0, 0, 0)
const groupItems = ref([])
const procModels = {}

const dataParams = ref({
  pageNo: 1,
  pageSize: 10
})
const agentDataList = ref({
  pages: 0,
  total: 0,
  records: []
})

function disableDate(time) {
  return time.getTime() < now - 86400000
}

onMounted(() => {
  loading.value = true
  loadModels().finally(() => getAgentList())
})

function loadModels() {
  return getProcGroupItemsList().then(res => {
    groupItems.value = res.data.filter(g => g.items.length > 0).map(group => {
      return {
        value: group.id,
        label: group.name,
        children: group.items.map(it => {
          procModels[it.code] = it.procName
          return {
            value: it.code,
            label: it.procName,
          }
        })
      }
    })
  }).catch(err => {
    ElMessage.error(err.msg)
  })
}

function getAgentRange(scope) {
  if (!scope) return '全部流程'
  return scope?.map(s => procModels[s]).join('、')
}

function getAgentList() {
  loading.value = true
  getAgentRulePage(dataParams.value).then(res => {
    agentDataList.value = res.data
    loading.value = false
    //赋予状态
    const current = dayjs();
    agentDataList.value.records.forEach(agent => {
      const startTime = dayjs(agent.timeRange[0])
      const endTime = dayjs(agent.timeRange[1])
      if (current.isBefore(startTime)) {
        agent.statusType = 'warning'
        agent.statusText = '待生效'
      } else if (current.isAfter(endTime)) {
        agent.statusType = 'info'
        agent.statusText = '已失效'
      } else {
        agent.statusType = 'primary'
        agent.statusText = '生效中'
      }
    })
  }).catch(err => {
    loading.value = false
  })
}

function addAgent() {
  agentDialog.value = true
  isAdd = true
  agentData.value = {
    target: [],
    reason: '',
    scope: [],
    isAll: true,
    timeRange: []
  }
}

function updateAgent(agent) {
  isAdd = false
  agentData.value = deepCopy(agent)
  agentData.value.target = [agentData.value.target]
  agentData.value.isAll = !Array.isArray(agent.scope)
  agentDialog.value = true
  nextTick(() => formRef.value.validate())
}

function deleteAgent(id) {
  ElMessageBox.confirm('确定要删除该代理规则吗？', '提示', {
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    type: 'warning'
  }).then(() => {
    deleteAgentRule(id).then(res => {
      ElMessage.success(res.data)
      getAgentList()
    }).catch(err => ElMessage.error(err.msg))
  })
}

function confirmAgent() {
  formRef.value.validate().then(() => {
    const params = Object.assign({}, agentData.value)
    params.target = params.target[0]
    const request = isAdd ? addAgentRule(params) : updateAgentRule(params)
    request.then(res => {
      agentDialog.value = false
      ElMessage.success(res.data)
      getAgentList()
    }).catch(err => ElMessage.error(err.msg))
  })
}

</script>

<style scoped lang="less">
.w-agent-item {
  padding: 5px;
  margin: 5px 0;
  border-radius: 5px;
  background-color: var(--el-bg-color-page);
}
</style>

// apps/web-react/src/views/workspace/ProcAgentPage.tsx
import React, { useCallback, useEffect, useState } from 'react';
import {
  Alert,
  Button,
  Cascader,
  Checkbox,
  DatePicker,
  Form,
  Input,
  Modal,
  Popconfirm,
  Space,
  Table,
  Tag,
  Typography,
  message,
} from 'antd';
import type { TableColumnsType } from 'antd';
import { DeleteOutlined, EditOutlined, PlusOutlined, SearchOutlined } from '@ant-design/icons';
import dayjs, { type Dayjs } from 'dayjs';
import {
  addAgentRule,
  deleteAgentRule,
  getAgentRulePage,
  updateAgentRule,
  type AgentRule,
} from '@/api/handover';
import { getProcGroupItemsList } from '@/api/model';
import { WAvatar } from '@/components/WAvatar';
import { WOrgPicker } from '@/components/WOrgPicker';
import { useTranslation } from '@/i18n';
import { formatMessage } from '@/utils/i18n';
import { useWflowStore } from '@/stores/wflow';
import type { OrgTarget } from '@/types/workflow';

interface GroupOption {
  value: string;
  label: string;
  children: Array<{ value: string; label: string }>;
}

interface AgentFormValues {
  target?: OrgTarget[];
  scope?: string[];
  timeRange?: [Dayjs, Dayjs];
  reason?: string;
}

const TargetPicker: React.FC<{
  value?: OrgTarget[];
  onChange?: (value: OrgTarget[]) => void;
  excludes?: string[];
}> = ({ value = [], onChange, excludes }) => {
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);
  return (
    <>
      <Space wrap>
        {value.map((user) => (
          <Tag
            key={user.id}
            color="blue"
            closable
            onClose={(event) => {
              event.preventDefault();
              onChange?.(value.filter((item) => item.id !== user.id));
            }}
          >
            {user.name}
          </Tag>
        ))}
        <Button size="small" type="primary" ghost onClick={() => setOpen(true)}>
          {t('workspace.agent.selectPerson')}
        </Button>
      </Space>
      <WOrgPicker
        open={open}
        title={t('workspace.agent.selectTargetTitle')}
        type="user"
        multiple={false}
        selected={value}
        excludes={excludes}
        onOk={(list) => onChange?.(list)}
        onCancel={() => setOpen(false)}
      />
    </>
  );
};

export const ProcAgentPage: React.FC = () => {
  const { t } = useTranslation();
  const { loginUser } = useWflowStore();
  const [form] = Form.useForm<AgentFormValues>();
  const [isAllScope, setIsAllScope] = useState(true);

  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [records, setRecords] = useState<AgentRule[]>([]);
  const [total, setTotal] = useState(0);
  const [pageNo, setPageNo] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const [groupOptions, setGroupOptions] = useState<GroupOption[]>([]);
  const [scopeLabels, setScopeLabels] = useState<Record<string, string>>({});

  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState<AgentRule | null>(null);

  const loadList = useCallback(async (p: number, s: number) => {
    setLoading(true);
    try {
      const res = await getAgentRulePage({ pageNo: p, pageSize: s });
      setRecords(res.data?.records || []);
      setTotal(res.data?.total || 0);
    } catch (e: any) {
      message.error(e?.msg || t('workspace.agent.loadFailed'));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadList(pageNo, pageSize);
  }, [pageNo, pageSize, loadList]);

  useEffect(() => {
    getProcGroupItemsList()
      .then((res) => {
        const labels: Record<string, string> = {};
        const options: GroupOption[] = (res.data || [])
          .filter((group: any) => group.items?.length)
          .map((group: any) => ({
            value: group.id,
            label: group.name,
            children: group.items.map((item: any) => {
              labels[item.code] = item.procName;
              return { value: item.code, label: item.procName };
            }),
          }));
        setScopeLabels(labels);
        setGroupOptions(options);
      })
      .catch((e: any) => message.error(e?.msg || t('workspace.search.groupFailed')));
  }, []);

  const scopeText = (scope?: string[] | null) => {
    if (!scope || scope.length === 0) return t('workspace.agent.allProcesses');
    return scope.map((code) => scopeLabels[code] || code).join(t('workspace.listSeparator'));
  };

  const statusTag = (timeRange?: string[]) => {
    const start = dayjs(timeRange?.[0]);
    const end = dayjs(timeRange?.[1]);
    const now = dayjs();
    if (now.isBefore(start)) return <Tag color="warning">{t('workspace.agent.notStarted')}</Tag>;
    if (now.isAfter(end)) return <Tag color="default">{t('workspace.agent.expired')}</Tag>;
    return <Tag color="processing">{t('workspace.agent.active')}</Tag>;
  };

  const handleAdd = () => {
    setEditing(null);
    setIsAllScope(true);
    setModalOpen(true);
  };

  const handleEdit = (row: AgentRule) => {
    setEditing(row);
    setIsAllScope(!Array.isArray(row.scope));
    setModalOpen(true);
  };

  useEffect(() => {
    if (!modalOpen) return;
    if (editing) {
      form.setFieldsValue({
        target: [{ id: editing.target.id, name: editing.target.name || '', type: 'user', avatar: editing.target.avatar }],
        scope: editing.scope || [],
        timeRange:
          editing.timeRange?.length === 2
            ? [dayjs(editing.timeRange[0]), dayjs(editing.timeRange[1])]
            : undefined,
        reason: editing.reason || '',
      });
    } else {
      form.resetFields();
      form.setFieldsValue({ target: [], scope: [], timeRange: undefined, reason: '' });
    }
  }, [modalOpen, editing, form]);

  const handleSubmit = async () => {
    let values: AgentFormValues;
    try {
      values = await form.validateFields();
    } catch {
      return;
    }
    const target = values.target?.[0];
    const range = values.timeRange;
    if (!target || !range) {
      message.warning(t('workspace.agent.incomplete'));
      return;
    }
    setSubmitting(true);
    try {
      const payload: AgentRule = {
        ...(editing?.id ? { id: editing.id } : {}),
        target: { id: target.id, name: target.name, avatar: target.avatar, type: target.type },
        scope: isAllScope ? null : values.scope || [],
        timeRange: [range[0].format('YYYY-MM-DD HH:mm:ss'), range[1].format('YYYY-MM-DD HH:mm:ss')],
        reason: values.reason || '',
      };
      const res = editing ? await updateAgentRule(payload) : await addAgentRule(payload);
      message.success(res.data || t('workspace.agent.saveSuccess'));
      setModalOpen(false);
      setEditing(null);
      form.resetFields();
      if (!editing && pageNo !== 1) setPageNo(1);
      else void loadList(pageNo, pageSize);
    } catch (e: any) {
      message.error(e?.msg || t('workspace.agent.saveFailed'));
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (id?: string) => {
    if (!id) return;
    try {
      const res = await deleteAgentRule(id);
      message.success(res.data || t('workspace.agent.deleteSuccess'));
      void loadList(pageNo, pageSize);
    } catch (e: any) {
      message.error(e?.msg || t('workspace.agent.deleteFailed'));
    }
  };

  const columns: TableColumnsType<AgentRule> = [
    {
      title: t('workspace.agent.target'),
      dataIndex: 'target',
      key: 'target',
      width: 160,
      render: (_: any, record: AgentRule) => (
        <WAvatar id={record.target?.id} name={record.target?.name} src={record.target?.avatar} size={24} />
      ),
    },
    {
      title: t('workspace.agent.scope'),
      dataIndex: 'scope',
      key: 'scope',
      ellipsis: true,
      render: (_: any, record: AgentRule) => scopeText(record.scope),
    },
    {
      title: t('workspace.table.status'),
      key: 'status',
      width: 100,
      render: (_: any, record: AgentRule) => statusTag(record.timeRange),
    },
    { title: t('workspace.agent.reason'), dataIndex: 'reason', key: 'reason', ellipsis: true },
    {
      title: t('workspace.agent.timeRange'),
      dataIndex: 'timeRange',
      key: 'timeRange',
      ellipsis: true,
      render: (range?: string[]) => (range?.length ? range.join(' ~ ') : '-'),
    },
    {
      title: t('workspace.table.action'),
      key: 'action',
      width: 160,
      render: (_: any, record: AgentRule) => (
        <Space size={4}>
          <Button type="link" icon={<EditOutlined />} onClick={() => handleEdit(record)}>
            {t('common.edit')}
          </Button>
          <Popconfirm
            title={t('workspace.agent.deleteConfirm')}
            okText={t('common.confirm')}
            cancelText={t('common.cancel')}
            onConfirm={() => handleDelete(record.id)}
          >
            <Button type="link" danger icon={<DeleteOutlined />}>
              {t('common.delete')}
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <Alert
        message={t('workspace.agent.intro')}
        type="info"
        showIcon
        style={{ marginBottom: 16 }}
      />

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <Typography.Title level={4} style={{ margin: 0 }}>
          {t('workspace.agent.ruleTitle')}
        </Typography.Title>
        <Space>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            {t('workspace.agent.addRule')}
          </Button>
          <Button icon={<SearchOutlined />} onClick={() => void loadList(pageNo, pageSize)}>
            {t('workspace.agent.query')}
          </Button>
        </Space>
      </div>

      <Table
        rowKey="id"
        loading={loading}
        dataSource={records}
        columns={columns}
        pagination={{
          current: pageNo,
          pageSize,
          total,
          showSizeChanger: true,
          pageSizeOptions: [10, 20, 50, 100],
          showTotal: (value) => formatMessage(t('workspace.table.totalRecords'), { total: value }),
          onChange: (nextPage, nextSize) => {
            setPageNo(nextPage);
            setPageSize(nextSize);
          },
        }}
      />

      <Modal
        title={t('workspace.agent.modalTitle')}
        open={modalOpen}
        width={650}
        confirmLoading={submitting}
        onCancel={() => setModalOpen(false)}
        onOk={handleSubmit}
        destroyOnHidden
      >
        <Form form={form} labelCol={{ span: 4 }} wrapperCol={{ span: 20 }} preserve={false}>
          <Form.Item
            label={t('workspace.agent.targetLabel')}
            name="target"
            rules={[{ required: true, message: t('workspace.agent.targetRule') }]}
          >
            <TargetPicker excludes={loginUser?.id ? [loginUser.id] : []} />
          </Form.Item>

          <Form.Item label={t('workspace.agent.scopeLabel')} style={{ marginBottom: 0 }}>
            <Checkbox checked={isAllScope} onChange={(event) => setIsAllScope(event.target.checked)}>
              {t('workspace.agent.allScope')}
            </Checkbox>
            <Form.Item
              name="scope"
              rules={[{ type: 'array', required: !isAllScope, message: t('workspace.agent.scopeRule') }]}
              style={{ display: isAllScope ? 'none' : 'block' }}
            >
              <Cascader
                multiple
                allowClear
                options={groupOptions}
                placeholder={t('workspace.agent.scopePlaceholder')}
                style={{ width: '100%', marginTop: 8 }}
              />
            </Form.Item>
            {isAllScope && (
              <Alert
                type="warning"
                showIcon
                style={{ marginTop: 8 }}
                message={t('workspace.agent.scopeWarning')}
              />
            )}
          </Form.Item>

          <Form.Item
            label={t('workspace.agent.timeLabel')}
            name="timeRange"
            rules={[{ required: true, message: t('workspace.agent.timeRule') }]}
          >
            <DatePicker.RangePicker
              showTime
              format="YYYY-MM-DD HH:mm:ss"
              separator={t('workspace.agent.timeSeparator')}
              placeholder={[t('workspace.agent.startPlaceholder'), t('workspace.agent.endPlaceholder')]}
              disabledDate={(current) => current && current < dayjs().startOf('day')}
              style={{ width: '100%' }}
            />
          </Form.Item>

          <Form.Item label={t('workspace.agent.reasonLabel')} name="reason">
            <Input.TextArea
              showCount
              maxLength={50}
              rows={3}
              placeholder={t('workspace.agent.reasonPlaceholder')}
            />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default ProcAgentPage;
