// apps/web-react/src/views/workspace/IdoPage.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Table, Tag, Button, message } from 'antd';
import type { TableColumnsType } from 'antd';
import { EyeOutlined } from '@ant-design/icons';
import { getIdoTasks } from '@/api/task';
import { SearchTools, type SearchParams } from '@/components/SearchTools';
import { useTranslation } from '@/i18n';
import { formatMessage } from '@/utils/i18n';
import { ProcessInstPreview } from './subs/ProcessInstPreview';
import { WAvatar } from '@/components/WAvatar';

const ACTION_LABELS: Record<string, { text: string; color: string }> = {
  complete: { text: 'workspace.action.complete', color: 'processing' },
  agree: { text: 'workspace.action.agree', color: 'success' },
  reject: { text: 'workspace.action.reject', color: 'error' },
  forward: { text: 'workspace.action.forward', color: 'default' },
  fallback: { text: 'workspace.action.fallback', color: 'warning' },
  beforeAdd: { text: 'workspace.action.beforeAdd', color: 'processing' },
  afterAdd: { text: 'workspace.action.afterAdd', color: 'processing' },
  revoke: { text: 'workspace.action.revoke', color: 'warning' },
  revise: { text: 'workspace.action.revise', color: 'warning' },
  withdraw: { text: 'workspace.action.withdraw', color: 'warning' },
  comment: { text: 'workspace.action.comment', color: 'default' },
  cancel: { text: 'workspace.action.cancel', color: 'default' },
};

export const IdoPage: React.FC = () => {
  const { t } = useTranslation();
  const [params, setParams] = useState<SearchParams>({});
  const paramsRef = useRef<SearchParams>(params);

  const [loading, setLoading] = useState(false);
  const [records, setRecords] = useState<any[]>([]);
  const [total, setTotal] = useState(0);
  const [pageNo, setPageNo] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const [previewOpen, setPreviewOpen] = useState(false);
  const [current, setCurrent] = useState<any>(null);

  const loadList = useCallback(async (p: number, s: number) => {
    setLoading(true);
    try {
      const res = await getIdoTasks({ pageNo: p, pageSize: s, ...paramsRef.current });
      setRecords(res.data?.records || []);
      setTotal(res.data?.total || 0);
    } catch (e: any) {
      message.error(e?.msg || t('workspace.ido.loadFailed'));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadList(pageNo, pageSize);
  }, [pageNo, pageSize, loadList]);

  const handleChange = (next: SearchParams) => {
    paramsRef.current = next;
    setParams(next);
  };

  const handleSearch = () => {
    if (pageNo === 1) void loadList(1, pageSize);
    else setPageNo(1);
  };

  const openInst = (row: any) => {
    setCurrent(row);
    setPreviewOpen(true);
  };

  const columns: TableColumnsType<any> = [
    {
      title: t('workspace.table.title'),
      dataIndex: 'title',
      key: 'title',
      ellipsis: true,
      render: (text: string, record: any) => (
        <a
          onClick={(event) => {
            event.stopPropagation();
            openInst(record);
          }}
        >
          {text || record.defineName}
        </a>
      ),
    },
    { title: t('workspace.table.processType'), dataIndex: 'defineName', key: 'defineName', width: 140 },
    { title: t('workspace.table.serialNumber'), dataIndex: 'instId', key: 'instId', width: 170, ellipsis: true },
    {
      title: t('workspace.table.initiator'),
      dataIndex: 'initiator',
      key: 'initiator',
      width: 130,
      render: (_: any, record: any) => (
        <WAvatar
          id={record.userId}
          name={record.username}
          src={record.avatar}
          status="agent"
          showStatus={record.userId !== record.submitter}
          size={24}
        />
      ),
    },
    { title: t('workspace.table.initiatorDept'), dataIndex: 'deptName', key: 'deptName', width: 120 },
    { title: t('workspace.table.processNode'), dataIndex: 'nodeName', key: 'nodeName', width: 130 },
    {
      title: t('workspace.table.handleAction'),
      dataIndex: 'action',
      key: 'action',
      width: 110,
      render: (action: string) => {
        const conf = ACTION_LABELS[action];
        return conf ? (
          <Tag color={conf.color}>{t(conf.text)}</Tag>
        ) : (
          <Tag>{action || t('workspace.action.processing')}</Tag>
        );
      },
    },
    { title: t('workspace.table.arriveTime'), dataIndex: 'createTime', key: 'createTime', width: 170 },
    { title: t('workspace.table.finishTime'), dataIndex: 'endTime', key: 'endTime', width: 170 },
    {
      title: t('workspace.table.action'),
      key: 'actionView',
      width: 100,
      fixed: 'right',
      render: (_: any, record: any) => (
        <Button
          type="link"
          icon={<EyeOutlined />}
          onClick={(event) => {
            event.stopPropagation();
            openInst(record);
          }}
        >
          {t('workspace.table.view')}
        </Button>
      ),
    },
  ];

  return (
    <div>
      <SearchTools
        value={params}
        onChange={handleChange}
        onSearch={handleSearch}
        showAction
        startDesc={t('workspace.search.taskArrival')}
      />

      <Table
        style={{ marginTop: 10 }}
        rowKey={(record) => record.taskId || `${record.instId}-${record.action}-${record.endTime}`}
        loading={loading}
        dataSource={records}
        columns={columns}
        onRow={(record) => ({ onClick: () => openInst(record) })}
        pagination={{
          current: pageNo,
          pageSize,
          total,
          showSizeChanger: true,
          pageSizeOptions: [10, 20, 50, 100],
          showTotal: (value) => formatMessage(t('workspace.table.totalRecords'), { total: value }),
          onChange: (nextPage, nextSize) => {
            setPageNo(nextPage);
            setPageSize(nextSize);
          },
        }}
      />

      <ProcessInstPreview
        open={previewOpen}
        instId={current?.instId || ''}
        onClose={() => setPreviewOpen(false)}
        onSuccess={() => void loadList(pageNo, pageSize)}
      />
    </div>
  );
};

export default IdoPage;

// apps/web/src/views/wflow/pages/workspace/IdoPage.vue
<script setup>
import {getIdoTasks} from "@/api/task.js";
import WAvatar from "../../common/WAvatar.vue";
import ProcessInstPreview from "./subs/ProcessInstPreview.vue";
import {ElMessage} from "element-plus";
import SearchTools from "./subs/SearchTools.vue";

const tbCellStyle = {
  background: 'var(--el-fill-color-lighter)',
  padding: '10px 0',
}
defineEmits(['confirm'])
const props = defineProps({
  code: { //默认筛选的流程编码
    type: String,
    default: null
  },
  pickerMode: Boolean
})

const datas = ref({
  pages: 0,
  records: [],
  total: 0
})
const params = reactive({
  pageNo: 1,
  pageSize: 10,
  code: props.code,
  title: null,
  action: null,
  startRange: [],
  endRange: []
})
const loading = ref(false)
const instPreview = ref()

const getIdoList = () => {
  loading.value = true
  const _params = Object.assign({}, params)
  _params.startRange = String(_params.startRange || [])
  _params.endRange = String(_params.endRange || [])
  getIdoTasks(_params).then(res => {
    loading.value = false
    datas.value = res.data
  }).catch(err => {
    loading.value = false
    ElMessage.error(err.msg)
  })
}

onMounted(() => {
  getIdoList()
})
</script>

<template>
  <div>
    <search-tools :show-type="!pickerMode" start-desc="任务到达" show-action @search="getIdoList" v-model="params"/>
    <div style="margin-top: 10px" v-loading="loading">
      <el-table :data="datas.records" :cell-style="{padding: '5px 0'}" :header-cell-style="tbCellStyle">
        <el-table-column show-overflow-tooltip prop="title" label="标题"></el-table-column>
        <el-table-column prop="defineName" label="流程类型"></el-table-column>
        <el-table-column show-overflow-tooltip prop="instId" label="流水号"></el-table-column>
        <el-table-column prop="initiator" label="发起人">
          <template #default="scope">
            <w-avatar :id="scope.row.userId" :name="scope.row.username" :src="scope.row.avatar"
                       status="agent" :show-status="scope.row.userId !== scope.row.submitter"/>
          </template>
        </el-table-column>
        <el-table-column show-overflow-tooltip prop="deptName" label="发起部门"></el-table-column>
        <el-table-column prop="nodeName" label="操作节点"></el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="scope">
            <el-tag type="success" v-if="scope.row.action === 'agree'">已同意</el-tag>
            <el-tag type="danger" v-else-if="scope.row.action === 'reject'">已拒绝</el-tag>
            <el-tag type="primary" v-else-if="scope.row.action === 'complete'">已办理</el-tag>
            <el-tag type="info" v-else-if="scope.row.action === 'forward'">已转交</el-tag>
            <el-tag type="warning" v-else-if="scope.row.action === 'revoke'">撤销流程</el-tag>
            <el-tag type="warning" v-else-if="scope.row.action === 'revise'">修改数据</el-tag>
            <el-tag type="warning" v-else-if="scope.row.action === 'withdraw'">已撤回</el-tag>
            <el-tag type="warning" v-else-if="scope.row.action === 'fallback'">已退回</el-tag>
            <el-tag type="info" v-else-if="scope.row.action === 'cancel'">已取消</el-tag>
            <el-tag type="primary" v-else-if="scope.row.action === 'beforeAdd'">前加签</el-tag>
            <el-tag type="primary" v-else-if="scope.row.action === 'afterAdd'">后加签</el-tag>
          </template>
        </el-table-column>
        <el-table-column show-overflow-tooltip prop="createTime" label="到达时间"></el-table-column>
        <el-table-column show-overflow-tooltip prop="endTime" label="处理时间"></el-table-column>
        <el-table-column fixed="right" width="150" label="操作">
          <template #default="scope">
            <el-button type="primary" link icon="View" @click="instPreview.open(scope.row.instId)">查看</el-button>
            <el-button link v-if="props.pickerMode" type="primary" icon="Pointer" @click="$emit('confirm', scope.row)">选择</el-button>
          </template>
        </el-table-column>
      </el-table>
      <process-inst-preview ref="instPreview" @change="getIdoList"/>
      <div style="margin-top: 20px; display: flex; justify-content: right">
        <el-pagination v-model:current-page="params.pageNo"
                       v-model:page-size="params.pageSize"
                       :page-sizes="[10, 20, 50, 100]"
                       :disabled="datas.pages === 0"
                       layout="total, sizes, prev, pager, next"
                       :total="datas.total" background
                       @size-change="getIdoList"
                       @current-change="getIdoList"/>
      </div>

    </div>
  </div>
</template>

<style scoped lang="less">

</style>
