// apps/web-react/src/views/workspace/TodoPage.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Table, Tag, Button, Space, Modal, message, Typography } from 'antd';
import type { TableColumnsType } from 'antd';
import { EyeOutlined, CheckCircleOutlined } from '@ant-design/icons';
import { claimTheTask, getTodoTasks } from '@/api/task';
import { SearchTools, type SearchParams } from '@/components/SearchTools';
import { useTranslation } from '@/i18n';
import { formatMessage } from '@/utils/i18n';
import { ProcessInstPreview } from './subs/ProcessInstPreview';
import { WAvatar } from '@/components/WAvatar';

export const TodoPage: React.FC = () => {
  const { t } = useTranslation();
  const [params, setParams] = useState<SearchParams>({});
  const paramsRef = useRef<SearchParams>(params);

  const [loading, setLoading] = useState(false);
  const [records, setRecords] = useState<any[]>([]);
  const [total, setTotal] = useState(0);
  const [pageNo, setPageNo] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const [previewOpen, setPreviewOpen] = useState(false);
  const [current, setCurrent] = useState<any>(null);

  const loadList = useCallback(async (p: number, s: number) => {
    setLoading(true);
    try {
      const res = await getTodoTasks({ pageNo: p, pageSize: s, ...paramsRef.current });
      setRecords(res.data?.records || []);
      setTotal(res.data?.total || 0);
    } catch (e: any) {
      message.error(e?.msg || t('workspace.todo.loadFailed'));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadList(pageNo, pageSize);
  }, [pageNo, pageSize, loadList]);

  const handleChange = (next: SearchParams) => {
    paramsRef.current = next;
    setParams(next);
  };

  const handleSearch = () => {
    if (pageNo === 1) void loadList(1, pageSize);
    else setPageNo(1);
  };

  const openInst = (row: any) => {
    setCurrent(row);
    setPreviewOpen(true);
  };

  const claimTask = (row: any) => {
    Modal.confirm({
      title: t('common.tip'),
      content: t('workspace.todo.claimConfirm'),
      okText: t('workspace.table.claim'),
      cancelText: t('common.cancel'),
      onOk: async () => {
        try {
          const res = await claimTheTask(row.taskId);
          message.success(res.data || t('workspace.todo.claimSuccess'));
          void loadList(pageNo, pageSize);
        } catch (e: any) {
          message.error(e?.msg || t('workspace.todo.claimFailed'));
        }
      },
    });
  };

  const columns: TableColumnsType<any> = [
    {
      title: t('workspace.table.title'),
      dataIndex: 'title',
      key: 'title',
      ellipsis: true,
      render: (text: string, record: any) => (
        <Typography.Link
          onClick={(event) => {
            event.stopPropagation();
            openInst(record);
          }}
        >
          {text || record.defineName}
        </Typography.Link>
      ),
    },
    { title: t('workspace.table.processType'), dataIndex: 'defineName', key: 'defineName', width: 140 },
    { title: t('workspace.table.serialNumber'), dataIndex: 'instId', key: 'instId', width: 170, ellipsis: true },
    {
      title: t('workspace.table.initiator'),
      dataIndex: 'initiator',
      key: 'initiator',
      width: 130,
      render: (_: any, record: any) => (
        <WAvatar
          id={record.initiator?.id}
          name={record.initiator?.name}
          src={record.initiator?.avatar}
          status="agent"
          showStatus={record.isAgent}
          size={24}
        />
      ),
    },
    { title: t('workspace.table.initiatorDept'), dataIndex: 'deptName', key: 'deptName', width: 120 },
    { title: t('workspace.table.currentNode'), dataIndex: 'currentNodeName', key: 'currentNodeName', width: 130 },
    {
      title: t('workspace.table.status'),
      key: 'status',
      width: 100,
      render: () => <Tag color="warning">{t('workspace.todo.pending')}</Tag>,
    },
    { title: t('workspace.table.taskArriveTime'), dataIndex: 'createTime', key: 'createTime', width: 170 },
    {
      title: t('workspace.table.action'),
      key: 'action',
      width: 160,
      fixed: 'right',
      render: (_: any, record: any) =>
        record.candidate === true ? (
          <Space size={4}>
            <Button
              type="link"
              icon={<EyeOutlined />}
              onClick={(event) => {
                event.stopPropagation();
                openInst(record);
              }}
            >
              {t('workspace.table.view')}
            </Button>
            <Button
              type="link"
              style={{ color: '#faad14' }}
              icon={<CheckCircleOutlined />}
              onClick={(event) => {
                event.stopPropagation();
                claimTask(record);
              }}
            >
              {t('workspace.table.claim')}
            </Button>
          </Space>
        ) : (
          <Button
            type="link"
            icon={<EyeOutlined />}
            onClick={(event) => {
              event.stopPropagation();
              openInst(record);
            }}
          >
            {t('workspace.table.handle')}
          </Button>
        ),
    },
  ];

  return (
    <div>
      <SearchTools
        value={params}
        onChange={handleChange}
        onSearch={handleSearch}
        startDesc={t('workspace.search.taskArrival')}
      />

      <Table
        style={{ marginTop: 10 }}
        rowKey={(record) => record.taskId || record.instId}
        loading={loading}
        dataSource={records}
        columns={columns}
        onRow={(record) => ({ onClick: () => openInst(record) })}
        pagination={{
          current: pageNo,
          pageSize,
          total,
          showSizeChanger: true,
          pageSizeOptions: [10, 20, 50, 100],
          showTotal: (value) => formatMessage(t('workspace.table.totalRecords'), { total: value }),
          onChange: (nextPage, nextSize) => {
            setPageNo(nextPage);
            setPageSize(nextSize);
          },
        }}
      />

      <ProcessInstPreview
        open={previewOpen}
        instId={current?.instId || ''}
        taskId={current?.taskId || undefined}
        nodeId={current?.currentNodeId || undefined}
        onClose={() => setPreviewOpen(false)}
        onSuccess={() => void loadList(pageNo, pageSize)}
      />
    </div>
  );
};

export default TodoPage;

// apps/web/src/views/wflow/pages/workspace/TodoPage.vue
<script setup>
import {claimTheTask, getTodoTasks} from "@/api/task.js";
import WAvatar from "../../common/WAvatar.vue";
import ProcessInstPreview from "./subs/ProcessInstPreview.vue";
import {ElMessage, ElMessageBox} from "element-plus";
import SearchTools from "./subs/SearchTools.vue";

const tbCellStyle = {
  background: 'var(--el-fill-color-lighter)',
  padding: '10px 0',
}
defineEmits(['confirm'])
const props = defineProps({
  code: { //默认筛选的流程编码
    type: String,
    default: null
  },
  pickerMode: Boolean
})

const datas = ref({
  pages: 0,
  records: [],
  total: 0
})
const params = reactive({
  pageNo: 1,
  pageSize: 10,
  code: props.code,
  title: null,
  startRange: [],
  endRange: []
})
const loading = ref(false)
const instPreview = ref()

const getTodoList = () => {
  loading.value = true
  const _params = Object.assign({}, params)
  _params.startRange = String(_params.startRange || [])
  getTodoTasks(_params).then(res => {
    loading.value = false
    datas.value = res.data
  }).catch(err => {
    loading.value = false
    ElMessage.error(err.msg)
  })
}

function claimTask(row) {
  ElMessageBox.confirm(`确定要签收该任务吗，签收后您需要处理该任务，是否确认？`, '提示', {
    confirmButtonText: '签收',
    cancelButtonText: '取消',
    type: 'warning'
  }).then(() => {
    claimTheTask(row.taskId).then(res => {
      getTodoList()
      ElMessage.success(res.data)
    }).catch(err => {
      ElMessage.error(err.msg || err)
    })
  })
}

function openInst(inst) {
  instPreview.value.open(inst.instId, inst.taskId, inst.currentNodeId)
}

onMounted(() => {
  getTodoList()
})
</script>

<template>
<div>
  <search-tools :show-type="!pickerMode" exclude-user start-desc="任务到达" @search="getTodoList" v-model="params"/>
  <div style="margin-top: 10px" v-loading="loading">
    <el-table :data="datas.records" :cell-style="{padding: '5px 0'}" :header-cell-style="tbCellStyle">
      <el-table-column show-overflow-tooltip prop="title" label="标题"></el-table-column>
      <el-table-column prop="defineName" label="流程类型"></el-table-column>
      <el-table-column show-overflow-tooltip prop="instId" label="流水号"></el-table-column>
      <el-table-column prop="initiator" label="发起人">
        <template #default="scope">
          <w-avatar :id="scope.row.initiator.id" :name="scope.row.initiator.name"
                    :src="scope.row.initiator.avatar" status="agent" :show-status="scope.row.isAgent"/>
        </template>
      </el-table-column>
      <el-table-column prop="deptName" label="发起部门"></el-table-column>
      <el-table-column prop="currentNodeName" label="当前节点"></el-table-column>
      <el-table-column label="状态" width="100">
        <el-tag type="warning">待处理</el-tag>
      </el-table-column>
      <el-table-column show-overflow-tooltip prop="createTime" label="任务到达时间"></el-table-column>
      <el-table-column fixed="right" width="150" label="操作">
        <template #default="scope">
          <template v-if="scope.row.candidate">
            <el-button type="primary" link icon="View" @click="openInst(scope.row)">查看</el-button>
            <el-button type="warning" link icon="Finished" @click="claimTask(scope.row)">签收</el-button>
          </template>
          <el-button type="primary" v-else link icon="Stamp" @click="openInst(scope.row)">处理</el-button>
          <el-button link v-if="props.pickerMode" type="primary" icon="Pointer" @click="$emit('confirm', scope.row)">选择</el-button>
        </template>
      </el-table-column>
    </el-table>
    <process-inst-preview ref="instPreview" @change="getTodoList"/>
    <div style="margin-top: 20px; display: flex; justify-content: right">
      <el-pagination v-model:current-page="params.pageNo"
                     v-model:page-size="params.pageSize"
                     :page-sizes="[10, 20, 50, 100]"
                     :disabled="datas.pages === 0"
                     layout="total, sizes, prev, pager, next"
                     :total="datas.total" background
                     @size-change="getTodoList"
                     @current-change="getTodoList"/>
    </div>

  </div>
</div>
</template>

<style scoped lang="less">

</style>
