// apps/web/src/views/wflow/design/form/base/component/CalcFormula.vue
<script setup>
import FormComponentMixin from "../../FormComponentMixin.js";
import request from "@/api/request.js";
import {compileHook, evaluateFormula} from '@/utils/form-runtime';

const props = defineProps({
  ...FormComponentMixin.props
})
const formData = inject('formData', {})
const emit = defineEmits([...FormComponentMixin.emits])
const _value = defineModel()
let calcFuc = null
const calcReg = /^[+\-*/()]+$/;
//const calcExplain = $debounce(doExc, 500)

const calcText = computed(() => {
  let text = ''
  props.config.props.explain.forEach(v => {
    if (v.label) {
      text += ` ${v.label} `
    }else {
      text += v
    }
  })
  return text
})

function doExc() {
  if (!calcFuc) {
    if (!props.config.props.isCustom) {
      const explainText = props.config.props.explain.map(v => {
        return v.value ? calcReg.test(v.value) ? `${v.value}` : ` formData.${v.value} ` : v
      }).join('')
      calcFuc = (data) => evaluateFormula(explainText, data)
    } else {
      calcFuc = compileHook(['formData', 'index', 'request'], props.config.props.jsCode)
    }
  }
  try {
    const result = calcFuc(formData.value, props.index || 0, request)
    if (result instanceof Promise) {
      result.then(val => _value.value = formatValue(val))
          .catch(() => _value.value = 0)
    } else {
      _value.value = formatValue(result)
    }
  } catch (e) {
    _value.value = 0
  }
}

function formatValue(val) {
  return parseFloat((val || 0).toFixed(props.config.props.precision || 0))
}

onMounted(() => {
  if (_value) {
    _value.value = 0
  }
})

watch(() => formData.value, () => {
  //这里每次表单值变化都会触发重新计算，为了加速就不消抖了先
  doExc()
}, {deep: true, immediate: true})
</script>

<template>
  <el-text v-if="mode === 'D'">
    {{config.props.prefix}}
    {{config.props.isCustom ? 'JS计算' : (calcText === '' ? '请设置公式' : calcText)}}
    {{config.props.suffix}}
  </el-text>
  <el-text v-else>{{config.props.prefix}} {{_value}} {{config.props.suffix}}</el-text>
</template>

<style scoped>

</style>

// apps/web-react/src/views/form/components/CalcFormula.tsx
import type { FC } from 'react';
import { useEffect, useRef } from 'react';
import { Typography } from 'antd';
import request from '@/api/request';
import { useTranslation } from '@/i18n';
import { compileHook, evaluateFormula } from '@/utils/form-runtime';
import type { FormComponentProps } from '../types';

interface ExplainToken {
  label?: string;
  value?: string;
}

const OPERATOR_RE = /^[+\-*/()]+$/;

function tokenToExpression(token: unknown): string {
  if (token === null || token === undefined) return '';
  if (typeof token === 'object') {
    const raw = (token as ExplainToken).value;
    if (raw === undefined || raw === null || raw === '') return '';
    const text = String(raw);
    return OPERATOR_RE.test(text) ? text : ` formData.${text} `;
  }
  return String(token);
}

function tokenToText(token: unknown): string {
  if (token === null || token === undefined) return '';
  if (typeof token === 'object') {
    const label = (token as ExplainToken).label;
    return label ? ` ${label} ` : '';
  }
  return String(token);
}

function formatValue(raw: unknown, precision: number): number {
  const num = Number(raw);
  if (!Number.isFinite(num)) return 0;
  return Number(num.toFixed(Math.min(20, Math.max(0, precision))));
}

export const CalcFormula: FC<FormComponentProps> = ({
  config,
  mode,
  value,
  onChange,
  scope,
  index,
}) => {
  const { t } = useTranslation();
  const props = config.props || {};
  const explain: unknown[] = Array.isArray(props.explain) ? props.explain : [];
  const precision = Number(props.precision ?? 2) || 0;
  const prefix = props.prefix ? String(props.prefix) : '';
  const suffix = props.suffix ? String(props.suffix) : '';
  const isCustom = props.isCustom === true;
  const jsCode = typeof props.jsCode === 'string' ? props.jsCode : '';
  const values = scope.values;
  const explainKey = JSON.stringify(explain);
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
    };
  }, []);

  useEffect(() => {
    const apply = (raw: unknown) => {
      const next = formatValue(raw, precision);
      if (!Object.is(next, value)) onChange(next);
    };
    try {
      if (isCustom) {
        const exec = compileHook(['formData', 'index', 'request'], jsCode);
        const result = exec(values, index ?? 0, request);
        if (result instanceof Promise) {
          result
            .then((resolved) => {
              if (mountedRef.current) apply(resolved);
            })
            .catch(() => {
              if (mountedRef.current) apply(0);
            });
        } else {
          apply(result);
        }
      } else {
        const expression = explain.map(tokenToExpression).join('').trim();
        if (!expression) {
          apply(0);
        } else {
          apply(evaluateFormula(expression, values));
        }
      }
    } catch {
      apply(0);
    }
  }, [values, value, isCustom, jsCode, precision, index, explainKey]);

  const formulaText = explain
    .map(tokenToText)
    .join('')
    .replace(/\s+/g, ' ')
    .trim();

  if (mode === 'D') {
    return (
      <Typography.Text>
        {[prefix, isCustom ? t('form.component.calc.js') : formulaText || t('form.component.calc.setFormula'), suffix]
          .filter((part) => part !== '')
          .join(' ')}
      </Typography.Text>
    );
  }

  const displayValue = value === undefined || value === null || value === '' ? 0 : value;

  return (
    <Typography.Text>
      {[prefix, String(displayValue), suffix].filter((part) => part !== '').join(' ')}
    </Typography.Text>
  );
};

export default CalcFormula;
