// apps/web/src/views/wflow/design/form/base/component/InstQuote.vue
<script setup>
import FormComponentMixin from "../../FormComponentMixin.js";
import WDialog from "../../../../common/WDialog.vue";
import WInstPicker from "../../../../common/WInstPicker.vue";
import {isEmpty} from "@/utils/GlobalFunc.js";
import {ElMessage, useFormItem} from "element-plus";
import ProcessInstPreview from "../../../../pages/workspace/subs/ProcessInstPreview.vue";

const props = defineProps({
  ...FormComponentMixin.props
})
const showDialog = ref(false)
const instanceRef = ref()
const _value = defineModel()
const {formItem} = useFormItem()
function confirm(inst) {
  if ((_value.value || []).some(v => v.value === inst.instId)) {
    ElMessage.warning('该流程已被添加')
  } else {
    showDialog.value = false
    const val = {
      value: inst.instId,
      label: inst.title
    }
    if (_value.value) _value.value.push(val)
    else _value.value = [val]
    formItem?.validate?.()
  }
}

function removeInst(i) {
  _value.value.splice(i, 1)
  formItem?.validate?.()
}
</script>

<template>
  <div class="w-inst-quote">
    <el-text type="warning" v-if="isEmpty(config.props.code)">请设置要引用的流程类型😥</el-text>
    <template v-else-if="mode === 'D' || mode === 'E'">
      <el-button icon="Plus" round @click="showDialog = true" style="margin-right: 10px"
                 v-if="!(!config.props.multiple && _value?.length > 0)">
        {{config.props.addText}}
      </el-button>
      <el-text v-if="!_value?.length > 0" class="w-placeholder">{{config.props.placeholder}}</el-text>
      <w-dialog close-free width="900" title="请选择流程实例" v-model="showDialog">
        <w-inst-picker :code="config.props.code" @confirm="confirm"/>
      </w-dialog>
    </template>
    <div class="w-inst-quote_item" v-for="(item, i) in _value" :key="item.value" @click="instanceRef.open(item.value)">
      <el-link>{{item.label}}</el-link>
      <el-icon @click.stop="removeInst(i)" v-if="mode === 'E'" class="w-inst-quote_close"><Close /></el-icon>
    </div>
    <process-inst-preview ref="instanceRef"/>
  </div>
</template>

<style lang="less" scoped>
.w-inst-quote {
  display: flex;
  flex-wrap: wrap;

  .w-inst-quote_item {
    cursor: pointer;
    display: flex;
    align-items: center;
    line-height: 20px;
    margin: 5px 15px 5px 0px;

    .w-inst-quote_close {
      margin-left: 5px;
      color: var(--el-color-info);
      padding: 2px;
      font-size: small;

      &:hover {
        border-radius: 50%;
        background-color: var(--el-fill-color-darker);
      }
    }
  }

  .w-placeholder {
    margin-left: 0 !important;
  }
}
</style>

// apps/web-react/src/views/form/components/InstQuote.tsx
import type { FC } from 'react';
import { useState } from 'react';
import { Button, Space, Typography, message } from 'antd';
import { CloseOutlined, PlusOutlined } from '@ant-design/icons';
import { WInstPicker } from '@/components/WInstPicker';
import { ProcessInstPreview } from '@/views/workspace/subs/ProcessInstPreview';
import { useTranslation } from '@/i18n';
import { isEmpty } from '../runtime';
import type { FormComponentProps } from '../types';

export interface InstQuoteItem {
  label: string;
  value: string;
}

export const InstQuote: FC<FormComponentProps> = ({ config, mode, value, onChange }) => {
  const { t } = useTranslation();
  const props = config.props || {};
  const code = props.code ? String(props.code) : '';
  const addText = props.addText || t('form.component.instQuote.defaultAdd');
  const multiple = props.multiple !== false;
  const placeholder = props.placeholder || '';
  const items: InstQuoteItem[] = Array.isArray(value) ? value : [];
  const [pickerOpen, setPickerOpen] = useState(false);
  const [previewId, setPreviewId] = useState<string | null>(null);

  const handlePick = (record: any) => {
    const instId = String(record?.instId ?? record?.id ?? '');
    if (!instId) return;
    if (items.some((item) => item.value === instId)) {
      message.warning(t('form.component.instQuote.alreadyAdded'));
      return;
    }
    onChange([
      ...items,
      { value: instId, label: String(record?.title ?? record?.name ?? instId) },
    ]);
    setPickerOpen(false);
  };

  if (isEmpty(code)) {
    return <Typography.Text type="warning">{t('form.component.instQuote.setProcessType')}</Typography.Text>;
  }

  const editable = mode === 'E' || mode === 'D';

  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 8 }}>
      {editable && (multiple || items.length === 0) ? (
        <Button icon={<PlusOutlined />} shape="round" onClick={() => setPickerOpen(true)}>
          {addText}
        </Button>
      ) : null}
      {editable && items.length === 0 && placeholder ? (
        <Typography.Text type="secondary">{placeholder}</Typography.Text>
      ) : null}
      {items.map((item, index) => (
        <Space key={`${item.value}-${index}`} size={6}>
          <Typography.Link onClick={() => setPreviewId(item.value)}>{item.label}</Typography.Link>
          {mode === 'E' ? (
            <CloseOutlined
              style={{ fontSize: 12, color: '#8c8c8c', cursor: 'pointer' }}
              onClick={() => onChange(items.filter((_, i) => i !== index))}
            />
          ) : null}
        </Space>
      ))}
      <WInstPicker
        open={pickerOpen}
        code={code}
        title={t('form.component.instQuote.pickerTitle')}
        onOk={handlePick}
        onCancel={() => setPickerOpen(false)}
      />
      {previewId ? (
        <ProcessInstPreview open instId={previewId} onClose={() => setPreviewId(null)} />
      ) : null}
    </div>
  );
};

export default InstQuote;
