// apps/web/src/views/wflow/design/form/base/component/Provinces.vue
<script setup>
import FormComponentMixin from "../../FormComponentMixin.js";
import { areaList } from '@vant/area-data'
import {isEmpty, useFormCpDefaultValue} from "@/utils/GlobalFunc.js";
import {dayjs, useFormItem} from "element-plus";

const props = defineProps({
  ...FormComponentMixin.props
})
const emit = defineEmits([...FormComponentMixin.emits])
const value = ref([])
const {formItem} = useFormItem()
const _value = computed({
  get() {
    if (!isEmpty(props.modelValue))
      return props.modelValue.split('-')
    else return []
  },
  set(val) {
    const value = Array.isArray(val) ? val.join('-') : val
    emit('update:modelValue', value)
  }
})
const treeData = ref([])
async function loadTreeData() {
  const province_list = Object.assign({}, areaList.province_list)
  const city_list = Object.assign({}, areaList.city_list)
  const county_list = Object.assign({}, areaList.county_list)
  treeData.value.length = 0
  for (const k in province_list) {
    let province = {
      label: province_list[k],
      value: province_list[k],
      children: [],
    }
    if (props.config.props.level >= 2) {
      for (const k2 in city_list) {
        let v = k2 - k
        if (v > 0 && v < 10000) {
          let city = {
            label: city_list[k2],
            value: city_list[k2],
            children: [],
          }
          if (props.config.props.level > 2) {
            for (const k3 in county_list) {
              let v2 = k3 - k2
              if (v2 > 0 && v2 < 100) {
                let county = {
                  label: county_list[k3],
                  value: county_list[k3],
                }
                delete county_list[k3]
                city.children.push(county)
              }
            }
          } else {
            city.children = undefined
          }
          delete city_list[k2]
          province.children.push(city)
        }
      }
    } else {
      province.children = undefined
    }
    delete province_list[k]
    treeData.value.push(province)
  }
}

onBeforeMount(loadTreeData)
useFormCpDefaultValue(props, _value)
</script>

<template>
  <el-cascader v-model="_value" style="width: 100%" v-if="mode !== 'V'" @change="formItem?.validate?.()"
               clearable separator="-" :options="treeData" :disabled="mode === 'R'"/>
  <el-text v-else>{{(_value || []).join('-')}}</el-text>
</template>

<style scoped>

</style>

// apps/web-react/src/views/form/components/Provinces.tsx
import type { FC } from 'react';
import { useMemo } from 'react';
import { Cascader, Typography } from 'antd';
import { areaList } from '@vant/area-data';
import { useTranslation } from '@/i18n';
import { isEmpty, useDefaultValue } from '../runtime';
import type { FormComponentProps } from '../types';

interface AreaOption {
  label: string;
  value: string;
  children?: AreaOption[];
}

function buildAreaOptions(level: number): AreaOption[] {
  const provinceList: Record<string, string> = { ...areaList.province_list };
  const cityList: Record<string, string> = { ...areaList.city_list };
  const countyList: Record<string, string> = { ...areaList.county_list };
  const tree: AreaOption[] = [];
  for (const provinceCode in provinceList) {
    const province: AreaOption = {
      label: provinceList[provinceCode],
      value: provinceList[provinceCode],
      children: [],
    };
    if (level >= 2) {
      for (const cityCode in cityList) {
        const diff = Number(cityCode) - Number(provinceCode);
        if (diff > 0 && diff < 10000) {
          const city: AreaOption = {
            label: cityList[cityCode],
            value: cityList[cityCode],
            children: [],
          };
          if (level > 2) {
            for (const countyCode in countyList) {
              const countyDiff = Number(countyCode) - Number(cityCode);
              if (countyDiff > 0 && countyDiff < 100) {
                city.children?.push({ label: countyList[countyCode], value: countyList[countyCode] });
                delete countyList[countyCode];
              }
            }
          } else {
            delete city.children;
          }
          province.children?.push(city);
          delete cityList[cityCode];
        }
      }
    } else {
      delete province.children;
    }
    delete provinceList[provinceCode];
    tree.push(province);
  }
  return tree;
}

export const Provinces: FC<FormComponentProps> = ({ config, mode, value, onChange }) => {
  const { t } = useTranslation();
  const props = config.props || {};
  const level = Math.min(3, Math.max(1, Number(props.level ?? 3) || 3));
  const placeholder = props.placeholder || t('form.component.provinces.placeholder');
  const options = useMemo(() => buildAreaOptions(level), [level]);

  useDefaultValue(config, mode, value, onChange);

  if (mode === 'V') {
    return <Typography.Text>{isEmpty(value) ? '' : String(value)}</Typography.Text>;
  }

  const selected = isEmpty(value) ? [] : String(value).split('-');

  return (
    <Cascader
      style={{ width: '100%' }}
      options={options}
      value={selected}
      placeholder={placeholder}
      displayRender={(labels) => labels.join('-')}
      disabled={mode === 'R'}
      onChange={(next) => onChange(Array.isArray(next) ? next.join('-') : String(next ?? ''))}
    />
  );
};

export default Provinces;
