// apps/web-react/src/components/WAvatar.tsx
import React, { useState } from 'react';
import { Avatar, Popover, Tag, Typography, Spin, Space } from 'antd';
import {
  CheckCircleFilled,
  CheckOutlined,
  CloseCircleFilled,
  CloseCircleOutlined,
  ClockCircleFilled,
  ExclamationCircleFilled,
  MessageOutlined,
  QuestionCircleFilled,
  RollbackOutlined,
  SendOutlined,
  UserOutlined,
  UserSwitchOutlined,
  WarningFilled,
  CloseOutlined,
} from '@ant-design/icons';
import { getUserDetail } from '@/api/org';
import { useTranslation } from '@/i18n';

interface WAvatarProps {
  id?: string | number;
  name?: string;
  src?: string;
  size?: number;
  agent?: boolean;
  showY?: boolean;
  closeable?: boolean;
  status?: string;
  showStatus?: boolean;
  showName?: boolean;
  onClose?: () => void;
}

export const WAvatar: React.FC<WAvatarProps> = ({
  id,
  name = '',
  src,
  size = 36,
  agent = false,
  showY = false,
  closeable = false,
  status,
  showStatus = false,
  showName = true,
  onClose,
}) => {
  const [loading, setLoading] = useState(false);
  const [detail, setDetail] = useState<any>(null);
  const { t } = useTranslation();

  const displayName = name.length > 2 ? name.slice(-2) : name;
  const statusVisible = showStatus || agent;

  const loadDetail = () => {
    if (!id || detail) return;
    setLoading(true);
    getUserDetail(String(id))
      .then((res) => {
        setDetail(res.data);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  };

  const getStatusIcon = () => {
    if (!statusVisible) return null;
    switch (agent ? 'agent' : status) {
      case 'agree':
      case 'pass':
      case 'PASS':
        return <CheckCircleFilled style={{ color: '#52c41a' }} />;
      case 'complete':
      case 'startup':
        return <CheckOutlined style={{ color: '#52c41a' }} />;
      case 'reject':
      case 'refuse':
      case 'REFUSE':
        return <CloseCircleFilled style={{ color: '#ff4d4f' }} />;
      case 'fallback':
        return <ExclamationCircleFilled style={{ color: '#faad14' }} />;
      case 'comment':
        return <MessageOutlined style={{ color: '#1677ff' }} />;
      case 'cc':
        return <SendOutlined style={{ color: '#1677ff' }} />;
      case 'cancel':
        return <CloseCircleOutlined style={{ color: '#8c8c8c' }} />;
      case 'revoke':
        return <RollbackOutlined style={{ color: '#8c8c8c' }} />;
      case 'agent':
        return <UserSwitchOutlined style={{ color: '#faad14' }} />;
      case 'revise':
        return <WarningFilled style={{ color: '#ff4d4f' }} />;
      case 'candidate':
        return <QuestionCircleFilled style={{ color: '#faad14' }} />;
      default:
        return <ClockCircleFilled style={{ color: '#1677ff' }} />;
    }
  };

  const content = (
    <div style={{ width: 220, padding: 4 }}>
      {loading ? (
        <Spin size="small" />
      ) : (
        <Space direction="vertical" size={6} style={{ width: '100%' }}>
          <Space>
            <Avatar size={36} src={src} icon={!src && !name ? <UserOutlined /> : undefined} style={{ backgroundColor: src ? 'transparent' : '#1677ff' }}>
              {displayName}
            </Avatar>
            <div>
              <Typography.Text strong>{name}</Typography.Text>
              {detail?.status && (
                <Tag color="success" style={{ marginLeft: 6 }}>
                  {detail.status}
                </Tag>
              )}
            </div>
          </Space>
          {detail?.deptName && <div>{t('workspace.avatar.dept')}: {detail.deptName}</div>}
          {detail?.mobile && <div>{t('workspace.avatar.mobile')}: {detail.mobile}</div>}
          {detail?.email && <div>{t('workspace.avatar.email')}: {detail.email}</div>}
        </Space>
      )}
    </div>
  );

  const avatarNode = (
    <div
      style={{
        display: 'inline-flex',
        flexDirection: showY ? 'column' : 'row',
        alignItems: 'center',
        position: 'relative',
        cursor: id ? 'pointer' : 'default',
      }}
    >
      <div style={{ position: 'relative', width: size, height: size, display: 'flex' }}>
        <Avatar
          size={size}
          src={src}
          icon={!src && !name ? <UserOutlined /> : undefined}
          style={{ backgroundColor: src ? 'transparent' : '#1677ff', fontSize: size * 0.4 }}
        >
          {displayName}
        </Avatar>
        {statusVisible && (
          <div
            style={{
              position: 'absolute',
              right: -4,
              bottom: -4,
              background: '#fff',
              borderRadius: '50%',
              lineHeight: 1,
              fontSize: Math.max(12, Math.round(size * 0.4)),
              display: 'flex',
            }}
          >
            {getStatusIcon()}
          </div>
        )}
        {closeable && (
          <CloseOutlined
            onClick={(e) => {
              e.stopPropagation();
              onClose?.();
            }}
            style={{
              position: 'absolute',
              right: -4,
              top: -4,
              background: '#fff',
              borderRadius: '50%',
              fontSize: 12,
              cursor: 'pointer',
            }}
          />
        )}
      </div>
      {showName && (
        <Typography.Text
          ellipsis
          style={{
            marginLeft: showY ? 0 : 8,
            marginTop: showY ? 4 : 0,
            maxWidth: 100,
            fontSize: size > 32 ? 14 : 12,
          }}
        >
          {name}
        </Typography.Text>
      )}
    </div>
  );

  if (!id) return avatarNode;

  return (
    <Popover content={content} trigger="click" onOpenChange={(next) => next && loadDetail()}>
      {avatarNode}
    </Popover>
  );
};

export default WAvatar;

// apps/web/src/views/wflow/common/WAvatar.vue
<script setup>
import {getUserDetail} from "@/api/org";
import {ElMessage} from "element-plus";

const props = defineProps({
  size: {
    type: Number,
    default: 38
  },
  id: [String, Number],
  src: String,
  name: String,
  showY: Boolean,
  closeable: Boolean,
  status: String,
  showStatus: Boolean,
  showName: {
    type: Boolean,
    default: true
  }
})

const userDetail = ref({});
const loading = ref(false);

const _name = computed(() => {
  if ((props.name || '').length > 2) {
    return props.name.substring(props.name.length - 2, props.name.length)
  }
  return props.name
})

const _status = computed(() => {
  if (!props.showStatus) return null
  switch (props.status) {
    case 'agree':
    case 'pass':
      return {icon: 'CircleCheckFilled', color: 'success'}
    case 'reject':
    case 'refuse':
      return {icon: 'CircleCloseFilled', color: 'danger'}
    case 'complete':
    case 'startup':
      return {icon: 'Checked', color: 'success'}
    case 'fallback':
      return {icon: 'Back', color: 'danger'}
    case 'comment':
      return {icon: 'Comment', color: 'primary'}
    case 'cc':
      return {icon: 'Promotion', color: 'primary'}
    case 'cancel':
      return {icon: 'CircleClose', color: 'info'}
    case 'candidate':
      return {icon: 'QuestionFilled', color: 'warning'}
    case 'revoke':
      return {icon: 'RefreshLeft', color: 'info'}
    case 'agent':
      return {icon: 'Avatar', color: 'warning'}
    case 'revise':
      return {icon: 'WarnTriangleFilled', color: 'danger'}
  }
  return {icon: 'Clock', color: 'warning'}
})

const nameSize = computed(() => {
  if (props.size > 40) {
    return 'large'
  } else if (props.size > 30) {
    return 'default'
  } else {
    return 'small'
  }
})

const loadUserDetail = () => {
  if (props.id) {
    loading.value = true
    getUserDetail(props.id).then(res => {
      loading.value = false
      userDetail.value = res.data
    }).catch(err => {
      loading.value = false
      ElMessage.error(err.msg)
    })
  } else {
    ElMessage.warning("组件未提供用户ID")
  }
}

</script>

<template>
  <el-popover :disabled="!id" placement="left-end" @show="loadUserDetail" :width="250" trigger="click">
    <template #reference>
      <div :class="{'w-avatar': true, 'w-avatar-y': showY}" :style="{flexDirection: showY ? 'column' : 'row', '--size': size + 'px'}">
        <div :style="{position: 'relative', height: size + 'px'}">
          <el-avatar :class="{'w-avatar-has': src}" :size="size" :src="src">{{ _name }}</el-avatar>
          <el-icon v-if="_status" class="w-avatar-status" :style="{color: `var(--el-color-${_status?.color})`}">
            <component :is="_status.icon"/>
          </el-icon>
          <el-icon v-if="closeable" class="w-avatar-close" @click.stop="$emit('close')">
            <CircleCloseFilled/>
          </el-icon>
        </div>
        <el-text v-if="showName" :size="nameSize" truncated style="margin-left: 5px">{{ name }}</el-text>
      </div>
    </template>
    <div class="w-user-detail" v-loading="loading">
      <div class="w-avatar" style="margin-bottom: 10px">
        <el-avatar :class="{'w-avatar-has': src}" :size="38" :src="src">{{ _name }}</el-avatar>
        <el-text truncated style="margin-left: 5px">{{ name }}</el-text>
        <el-divider direction="vertical"/>
        <el-text size="small" type="success">{{ userDetail.status }}</el-text>
      </div>
      <el-form label-width="45px">
        <el-form-item label="部门">
          <el-button link type="info" style="margin: 0 5px" v-for="dept in (userDetail.depts || [])">
            {{ dept.name }}
          </el-button>
        </el-form-item>
        <el-form-item label="角色" v-if="(userDetail.roles || []).length > 0">
          <el-tag size="small" style="margin: 0 5px" v-for="dept in (userDetail.roles || [])">{{ dept.name }}</el-tag>
        </el-form-item>
        <el-form-item label="手机">
          <el-button type="primary" link>{{ userDetail.mobile }}</el-button>
        </el-form-item>
        <el-form-item label="邮箱">
          <el-button type="primary" link>{{ userDetail.email }}</el-button>
        </el-form-item>
        <el-form-item label="格言">
          <el-text>{{ userDetail.motto }}</el-text>
        </el-form-item>
      </el-form>
    </div>
  </el-popover>
</template>

<style scoped lang="less">
.w-avatar {
  display: flex;
  cursor: pointer;
  align-items: center;

  .w-avatar-close {
    position: absolute;
    right: -5px;
    top: -2px;
    color: var(--el-color-info);
    border-radius: 50%;
    background: var(--el-bg-color);
  }

  .w-avatar-status {
    font-size: 14px;
    position: absolute;
    left: calc(var(--size) - 12px);
    top: calc(var(--size) - 12px);
    background: var(--el-bg-color);
    border-radius: 50%;
    padding: 1px;
  }

  .w-avatar-has {
    background: none !important;
  }

  .el-avatar {
    background: var(--el-color-primary)
  }
}

.w-user-detail {
  :deep(.el-form-item) {
    margin-bottom: 0 !important;
  }
}

.w-avatar-y {
  width: 80px;
  margin-top: 5px;
  overflow: hidden;
}
</style>
